### ISSUE TITLE
Modify paths using environment variables

### ISSUE THREAD

**Issue by xmha97** [filips123/PWAsForFirefox#109]
Hi @filips123 
Why is runtime installed for the current user?
![image](https://user-images.githubusercontent.com/23485114/147456184-57ef3587-9afe-4ece-be3f-2139b2f3a8dd.png)
I think runtime should be installed in "Program Files" because I do not want to install a separate Firefox for each user.

**Comment by filips123** [comment]
Originally runtime was installed for all users, but then I changed it (https://github.com/filips123/PWAsForFirefox/commit/df05306fae01916834575d9d6bd5e371a68ee919, #10, #24) to a user-specific directory. This is because installing it for all users requires that directory to be writable by all users, which isn't so good for security and could cause other problems. If you still want to globally install runtime, you will have to [edit the source code](https://github.com/filips123/PWAsForFirefox/blob/main/native/src/components/runtime.rs#L74-L77) (change `dirs.userdata.join("runtime")` to `dirs.sysdata.join("runtime")`) and manually build and install the project.

**Comment by xmha97** [comment]
OK, Thanks for your explanation.

**Comment by xmha97** [comment]
How I can change the runtime path?
Do I have to create symlinks? `%ProgramFiles%\FirefoxPWA\runtime` to `%AppData%\FirefoxPWA\runtime`

**Comment by filips123** [comment]
Currently, you cannot modify any paths using environment variables. However, you could use symlinks for each user to some global directory:

1. Move existing runtime from `%AppData%\FirefoxPWA\runtime` to `%ProgramFiles%\FirefoxPWA\runtime`. Do this only for one user, just so you will have one global copy of the runtime.
2. Then, for each user you have, remove old its runtime (if it exists) and symlink `%AppData%\FirefoxPWA\runtime` to `%ProgramFiles%\FirefoxPWA\runtime` (with your command).
3. You may also have to make `%ProgramFiles%\FirefoxPWA\runtime` writable by all users for Firefox updates to work, but I'm not sure.

This way PWAsForFirefox will think runtime is installed for each user, but you will have only one global copy of it.

**Comment by xmha97** [comment]
Will I can modify paths using environment variables in the future?

**Comment by filips123** [comment]
Yes, I will probably implement something in the future.
