### ISSUE TITLE
Portable version

### ISSUE THREAD

**Issue by xmha97** [filips123/PWAsForFirefox#118]
Hi @filips123,

I have been using portable apps for a long time:
![image](https://user-images.githubusercontent.com/23485114/147948962-3953813c-8f0d-4eff-b588-5ea94d4fe727.png)
Now I want to use my PWAs on a USB drive!

The prerequisite is to be able to change the default paths on `firefoxpwa.json` not environment variables.
![image](https://user-images.githubusercontent.com/23485114/147949920-a089c378-cfbf-4d4a-9857-011bbbd62a42.png)

Maybe this issue will cover #109

**Comment by filips123** [comment]
`firefoxpwa.json` is just a [native messaging manifest](https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/Native_manifests) for Firefox. It's only read and used by Firefox itself, so it can't be used to change the default paths. Maybe PWAsForFirefox could read paths from this file at startup, but this is a bit weird (file was not meant for this), and it would still need to find the location of this file through the registry (which isn't so portable). I also can't use other files for config, because changing the path would actually change where those files should be located, so unfortunately, using environment variables seems to be the only viable option.

However, I will try to find some other way to do this, and probably (if I'm successful) package PWAsForFirefox as a PortableApps.com app.

**Comment by xmha97** [comment]
OK, Thanks.

**Comment by filips123** [comment]
Unfortunately, I wasn't able to add PortableApps.com support for this release, because PortableApps.com do not support apps with native messaging. I will still try to find out if there is a way to support them in the future.

However, there is now (since 2.0.0) a way to install your web apps and data on a USB, although not 100% portable and requires a bit extra work. PWAsForFirefox will still need to be installed on your computer(s), but web apps themselves (and their data) can be on a USB drive:

1. Install PWAsForFirefox on every computer where you want to use PWAs. You will also be able to do this per-user, without requiring an administrator account.
2. Also on every computer, create an `FFPWA_USERDATA` environment variable that points to some directory on a USB drive (for example, `F:\Data\WebApps`). This is where your web apps and profiles will be stored.
3. Use PWAsForFirefox as normal. When you move to another computer, open the extension settings and run "Update web apps" t create start menu entries.

However, this will leave trails of web apps on your computer (start menu entries and some registry entries) even after you unplug your USB, so it may not be good to use it on public computers.

**Comment by filips123** [comment]
I've now added proper PortableApps.com support which will be released in 2.3.0.

The project is now also available as a `.paf.exe` installer (which can be downloaded from the releases page) and can be used with the PortableApps.com Platform. Installed web apps will be added as new entries to its menu and it shouldn't leave other trails on the computer.

To use the extension with the portable version, you will have to start the PWAsForFirefox Portable program, so Firefox recognizes the portable version. Other documentation is available in the `help.html` file.

**Comment by xmha97** [comment]
Now, I have tested the PortableApps.com version and it is working fine.
Thanks for supporting the portable feature. <3
