### ISSUE TITLE
How to open links in default Browser

### ISSUE THREAD

**Issue by lenicyl** [filips123/PWAsForFirefox#119]
I know #108 exists, however i have a different request

I made a PWA for `https://discord.com/channels/@me` but when i click on a link it opens the link inside the PWA.
Is it possible to set it so that any website NOT starting with `https://discord.com` opens in the default browser ??

The `Open Out of scope URL's in default browser` option doesnt really work for sites like this to me 

Thanks.

**Comment by filips123** [comment]
Do you have a problem with "Open Out of scope URL's in default browser" because it redirects Discord's login page (and all other Discord pages outside `/channels/@me`) to the default browser? If so, you have two options to prevent this:

* Recreate (editing won't work) Discord PWA and set `htttps://discord.com/` as a start URL. Unlike the other solution, this will also hide URL bar on Discord domain. This is the preferred solution, as this is how it would probably work if Discord was an actual PWA (with web app manifest and properly set scope).

* Inside PWA settings, add `discord.com` domain to "Domains always allowed to be opened in the PWA browser". This will still treat pages outside `/channels/@me` (but with `discord.com` domain) as out of scope pages (e.g. URL bar will be displayed), but they won't be redirected to default browser.

**Comment by lenicyl** [comment]
Thank you for the quick help, that worked as intended !!!
