### ISSUE TITLE
Sync extension data with FirefoxSync /or/ manual import/export of data

### ISSUE THREAD

**Issue by AlexDumi29** [filips123/PWAsForFirefox#130]
#### Is your feature request related to a problem?
Yes, I have to create the same web app all over again on each of my devices.
#### Please add a clear description of the problem you are seeking to solve with this feature request
Having sync or import/export functionality for the webapps and the profiles (presumably using firefox directly, but anything will do) so I wouldn't have to do it separately on all of my devices and OS's.

#### Describe the solution you'd like clearly and concisely
The extension should have the ability to import and export the current apps, profiles and settings, preferably by itself using some sort of sync, but even manual import/export functionality would be great

**Comment by filips123** [comment]
You can manually copy `config.json` file and `profiles` directory and then run "Update web apps" from the extension settings on a target computer. This will copy all your installed web apps, including their data, and register them to the OS.

I plan to improve project documentation/instructions soon, and I will include those instructions there. Unfortunately, proper/continuous sync using Firefox Sync isn't possible, because most data are stored outside the extension. However, I think you could still sign into Firefox Account from PWA profiles, so at least data from web apps are synced.
