### ISSUE TITLE
Allow domain paths to open in default browser instead of PWA

### ISSUE THREAD

**Issue by markcellus** [filips123/PWAsForFirefox#150]
### Problem Description

Certain websites use the same domain (but different paths) for outbound links. I'd like these links to be opened in the default browser (not in the PWA). But checking "Open out of scope URLs in a default browser (can break some websites)" setting doesn't seem to open the links in default browser. Like links in the description box of a Youtube video for instance begin with https://www.youtube.com/redirect=http://pathtosomeotherwebsite.com.

### Proposed Solution

Allow some way for the "Open out of scope URLs in a default browser (can break some websites)" setting to be applied to only paths of a domain--but all other paths should still continue to open in PWA. Is this possible? Thanks!

**Comment by markcellus** [comment]
Sorry I mispoke on my earlier request, I updated the description of the issue accordingly.

**Comment by filips123** [comment]
I can probably implement this, but is there a reason why you couldn't just use existing domain list? I think it shouldn't matter that https://www.youtube.com/redirect= is opened in PWA, because once it is redirected to an actual website, it should automatically open in default browser.

**Comment by danieltroger** [comment]
I'm having this issue - when I click on a link in a PWA'd site it just redirects the web app instead of opening in my default browser.

<img width="842" alt="Screenshot 2023-04-26 at 13 45 27" src="https://user-images.githubusercontent.com/4047180/234565172-fbd44241-f925-4fcb-a118-c2d70b279708.png">

**Comment by danieltroger** [comment]
I found https://github.com/filips123/PWAsForFirefox/issues/140#issuecomment-1086611157 which describes what I wanted but now it just starts loading my slack PWA window forever and my linear PWA doesn't open (I'm using Velja to bind linear links to the linear PWA).

**Comment by filips123** [comment]
This probably happens because Slack uses SSO for login with multiple domains, so PWAsForFirefox does not know that all of those domains should be opened as PWAs. To solve this, you can add a list of domains that Slack uses to the "Domains always allowed to be opened in the PWA browser" option in the settings. For Slack, that should be `slack.com,app.slack.com,your-workspace-name.slack.com`. (In the future, you will be able to use wildcards, but this isn't implemented yet.)

For Linear, I think that you have to add `linear.app,accounts.google.com` and maybe other domains that it uses.
