### ISSUE TITLE
[Feature Request] Option to disable the Session Restore crash recovery feature

### ISSUE THREAD

**Issue by IceDBorn** [filips123/PWAsForFirefox#163]
### Problem Description

I have a lot of PWAs which autostart with my system. The problem is that when I'm rebooting using the terminal, those PWAs always ask if I want to restore my previous session or start a new one, which is annoying.

### Proposed Solution

Add an option to the settings, that toggles `browser.sessionstore.resume_from_crash`

### Additional Information

I can look into it and create a PR if necessary.

**Comment by filips123** [comment]
`browser.sessionstore.resume_from_crash` is disabled by default because it caused some problems when restoring sessions (#86), so I'm not sure how useful would toggle in settings be. But you can still toggle it through `about:config` (and you can open `about:config` if you press F6 and enter the URL).

**Comment by filips123** [comment]
It seems session restore does generally not behave completely as expected, so I will close this issue in favour of #175.
