### ISSUE TITLE
PWA not working on Whatsapp Web  nor Tweetdeck, but for others.

### ISSUE THREAD

**Issue by InDoubt** [filips123/PWAsForFirefox#172]
I just starting in a new Mac from scratch.
In my previous Mac (limited to High Sierra) I installed PWA and successfully got Whatsapp Web, Tweetdeck and CBS News sites  installed as apps.

Now, in Monterrey, I can not get Whatsapp Web or Tweetdeck as apps.
The Icon in the search bar is just not there. So I can not convert in apps those sites.
Still, a fully functional  ⍗ "install this site" icon appears in CBS News, Github and others.

Can you give me some advice to fix this issue, please?
Thank you in advance!

macOS Monterrey 12.4
Retina 5k, 27', 2015
3.2 ghz i5
16 gb ram
AMD Radeon R9 M380 2 GB
FF 101.0.1
PWA 1.4.2 June 18 2022 (don't now how to get * PWAsForFirefox extension version: * PWAsForFirefox native version:)
Installed through: https://addons.mozilla.org/en-US/firefox/addon/pwas-for-firefox/
![Screen Shot 2022-06-18 at 9 31 52 AM](https://user-images.githubusercontent.com/17437998/174440001-c76b535c-27c1-430e-8e81-a91f060fa6df.jpg)

**Comment by filips123** [comment]
That's because Whatsapp Web and Tweetdeck are not actual PWAs as they don't have Web App Manifest, and PWAsForFirefox by default only shows the icon on PWAs. However, you can still install them through the main extension popup ("Install current site" button at the bottom of the web apps list). You can also set "Display address bar widget" to "Always" in the extension settings so the icon appears on all websites.

**Comment by InDoubt** [comment]
Thank you very much, filps!
Works awesomely!
