### ISSUE TITLE
Firefox Nightly Support

### ISSUE THREAD

**Issue by vicelo23** [filips123/PWAsForFirefox#173]
### Problem Description

PWAsForFirefox can't use our Firefox Nightly installation for accessing cookies, extensions, sync etc.

### Proposed Solution

Make it use Firefox Nightly if extension running on Firefox Nightly. This can make things easier since we will already have our extensions and cookies of the site we're using.

**Comment by filips123** [comment]
PWAsForFirefox already supports using Firefox Nightly as a PWA runtime, but you will need to manually copy it to the correct directory. On Windows, this means you will probably have to copy contents of `C:\Program Files\Firefox Nightly\` to `%APPDATA%\FirefoxPWA\runtime\`. For runtime locations on other OSes, see [#5 here](https://github.com/filips123/PWAsForFirefox/wiki/Frequently-Asked-Questions).

However, PWAs will still use a separate profile. This is because PWAsForFirefox needs to modify Firefox UI so it looks more like a real app, and this requires a separate profile. In addition to this, some settings need to be different when running as PWA and running as a normal browser, which also requires a separate profile.

If you want to sync data between your main and PWA profile, I recommend using Firefox Account. If you want to sync data that Firefox Account cannot sync, you could probably symlink some files from your normal profile as I described [here](https://github.com/filips123/PWAsForFirefox/issues/135#issuecomment-1048098706). However, please be aware that this is unsupported and I don't know if it works perfectly.
