### ISSUE TITLE
Allow modifying/disabling keyboard shortcut for toggling icon bar

### ISSUE THREAD

**Issue by mirenradia** [filips123/PWAsForFirefox#177]
### Problem Description

Currently if you have enabled a hiding icon bar (by setting the config option `firefoxpwa.enableHidingIconBar = true`), the only keyboard shortcut to toggle this is Ctrl+Alt.

### Proposed Solution

It would be nice if this keyboard shortcut could be modified or disabled (the icon bar can still be toggled by right-clicking the title bar).

### Additional Information

I guess it's my fault but I use Ctrl+Alt+\<arrow key\> to navigate between desktops so often find myself toggling the icon bar on my firefox PWAs accidentally.

**Comment by filips123** [comment]
Allowing users to modify a keyboard shortcut (without them having to modify the code) could add quite a lot of complexity to the code due to how it's currently implemented. I'm also not sure about optionally disabling it as it also adds a bit of additional complexity with additional preference.

However, I can change the shortcut to only trigger once all keys have been released and only if only Ctrl and Alt keys have been pressed. This way, the icon bar shouldn't toggle on your Ctrl+Alt+<arrow key> shortcuts. I hope that would be enough, but I can probably still implement a preference to disable that shortcut if needed.

**Comment by mirenradia** [comment]
> However, I can change the shortcut to only trigger once all keys have been released and only if only Ctrl and Alt keys have been pressed. This way, the icon bar shouldn't toggle on your Ctrl+Alt+<arrow key> shortcuts. I hope that would be enough, but I can probably still implement a preference to disable that shortcut if needed.

That would probably be enough for my needs although it would still be nice to be able to disable the shortcut with a preference.

**Comment by mirenradia** [comment]
Perhaps I should create a new issue but after the update to 2.0.1, I can no longer hide the icon bar at all. If I right-click on the bar and deselect "Icon Bar" or press Ctrl+Alt, it shows as deselected in the right-click menu but the bar is still visible.

**Comment by filips123** [comment]
It works for me... Can you check if `firefoxpwa.enableHidingIconBar` is still enabled in `about:config` and if it works when you try to hide it from the Firefox customize page? Also please check if it works in a new web app profile (after enabling `firefoxpwa.enableHidingIconBar`).

**Comment by mirenradia** [comment]
I tried creating a new PWA in a new profile and enabled `firefoxpwa.enableHidingIconBar` (I don't think you can see the 'Icon Bar' option in the right-click menu for it without this enabled) but it still doesn't work for me. Should I create a fresh issue for it?

**Comment by mirenradia** [comment]
Sorry, I also tried hiding it from the 'Customize Toolbar" page as well.

**Comment by filips123** [comment]
Yeah, please create a new issue, and also specify which OS and dektop environment you use.
