### ISSUE TITLE
Add helper scripts for building from source

### ISSUE THREAD

**Issue by JJRcop** [filips123/PWAsForFirefox#193]
### Problem Description
Building from source requires hand-editing some files, which is slightly tedious, but only trivially so.

### Proposed Solution
Add some helper scripts under `native/` and `extension/` in both windows batch and POSIX sh formats, (or node.js, cross platform) They could simply take an argument which is the version to replace, maybe perform validation that it confirms to the proper version format, and edit the files themselves.

If you want to be fancy, they could look at the current git tag from [`git describe`][git-describe] and use that (maybe filtering out the leading "v")

### Additional Information
I am able to make these myself, but I have a weird head on my shoulders and will probably delay for a while until eventually getting around to it, sorry.

[git-describe]: https://git-scm.com/docs/git-describe/2.37.1

**Comment by filips123** [comment]
I agree that would be useful. Parsing the Git tag would also be very nice. Something similar is already done inside GitHub Actions for publishing, so I can probably just copy and slightly adjust that to some reusable scripts.

For `native/`, it could be inside the existing `Makefile.toml`, as `cargo-make` can automatically transpile (basic) bash commands to Windows batch, or use cross-platform [duckscript](https://sagiegurari.github.io/duckscript/) in case transpiling doesn't work. This would also be useful because then you could just run something like `makers prepare` and then already existing `makers install` to install the package (but they should be separate commands)

For `extension/`, Node.js script could be used.
