### ISSUE TITLE
Duplicate entry for default apps in Windows 11

### ISSUE THREAD

**Issue by picknassaro** [filips123/PWAsForFirefox#205]
Please either change the name or the icon for the browser exe located at C:\Users\USERNAME\AppData\Roaming\FirefoxPWA\runtime\firefox.exe. The attached screenshot shows how it is impossible to tell which Firefox is the Firefox that was installed by the PWAsForFirefox Extension and which one is the original Firefox installed in C:\Program Files\

![187539109-5990f883-d6b2-4bcf-aceb-9aa7a41618ba](https://user-images.githubusercontent.com/31928723/187542045-c281fc35-e127-439e-b3c5-69e2081e4746.png)

**Comment by filips123** [comment]
Well, the PWAsForFirefox Firefox entry shouldn't be there in the first place, and I'm not sure why it got added. I disabled checking for default browser for PWAs, but maybe there are still some things that are enabled and cause this (also see #210 and #211).

**Comment by filips123** [comment]
I think Firefox adds itself to that list if you try to make it a default browser. Apparently (#211), there were still some default browser prompts that weren't properly disabled, so maybe you clicked on one of those? I think they should now (ac79e551b068d8fe432edc97f0318cff9dd53c76) be disabled, so this issue is probably also fixed.

You can probably remove duplicate Firefox from that list with some registry editing...

**Comment by filips123** [comment]
I'll close this issue because I think it has been fixed. The only currently remaining issue about default browser prompts is #210.
