### ISSUE TITLE
Theme issue

### ISSUE THREAD

**Issue by Hazem42** [filips123/PWAsForFirefox#209]
### Description

I'm using a custom theme for windows 10, It broke the theme for Firefox's close/minimize/maximize buttons (I think it gets reset to the default theme), I was able to fix it in Firefox by adding this to userChrome.css
```
.titlebar-button{
  background-color: transparent !important;
  -moz-context-properties: stroke !important;
  stroke: currentColor !important;
}
.titlebar-button:hover{ background-color: hsla(0,0%,100%,.32) !important }
.titlebar-close:hover{ background-color: hsl(355,86%,49%) !important }

.titlebar-close{ list-style-image: url(chrome://browser/skin/window-controls/close.svg) !important }
.titlebar-min{ list-style-image: url(chrome://browser/skin/window-controls/minimize.svg) !important }
.titlebar-max{ list-style-image: url(chrome://browser/skin/window-controls/maximize.svg) !important }
.titlebar-restore{ list-style-image: url(chrome://browser/skin/window-controls/restore.svg) !important }
```
but I couldn't fix it for the web-apps, I tried adding the same to `AppData\Local\Programs\FirefoxPWA\userchrome\profile\chrome\pwa\content\browser.css`, but it didn't fix it.

Not a big deal, I just want to know if I can fix it or not.
Thank you.

![Screenshot (26)](https://user-images.githubusercontent.com/89294365/189017306-87f71b9c-d6de-49db-885c-b8c7dd1f2a1b.png)

**Comment by filips123** [comment]
You shouldn't be using `chrome/pwa/content/browser.css` because it gets overwritten on PWAsForFirefox updates. Instead, just use a normal `chrome/userChrome.css` inside the web app's profile and enable `toolkit.legacyUserProfileCustomizations.stylesheets` in `about:config`.

If this doesn't fix the issue, can you share your custom theme please, as it would be easier to debug why it doesn't work?

**Comment by Hazem42** [comment]
**Didn't work.**
I have `toolkit.legacyUserProfileCustomizations.stylesheets` enabled. In `AppData\Local\Programs\FirefoxPWA\userchrome\profile\chrome` I created a `userChrome.css` with 
```
.titlebar-button{
  background-color: transparent !important;
  -moz-context-properties: stroke !important;
  stroke: currentColor !important;
}
.titlebar-button:hover{ background-color: hsla(0,0%,100%,.32) !important }
.titlebar-close:hover{ background-color: hsl(355,86%,49%) !important }

.titlebar-close{ list-style-image: url(chrome://browser/skin/window-controls/close.svg) !important }
.titlebar-min{ list-style-image: url(chrome://browser/skin/window-controls/minimize.svg) !important }
.titlebar-max{ list-style-image: url(chrome://browser/skin/window-controls/maximize.svg) !important }
.titlebar-restore{ list-style-image: url(chrome://browser/skin/window-controls/restore.svg) !important }
```
but it didn't work, even though it's working fine in Firefox.
I'm using [this](https://github.com/ranmaru22/firefox-vertical-tabs.git) to get vertical tabs in Firefox, I just added this to it
```
#mainPopupSet menupopup {
  /* Text: "Toolbar Icons and Text", Background: "Toolbar Color" */
  --menu-color: var(--toolbar-color) !important;
  --menu-background-color: var(--toolbar-bgcolor) !important;
  --menu-border-color: var(--toolbar-color) !important;
  /* Create a neutral hover background (25% white haze) */
  --menuitem-hover-background-color: rgba(255, 255, 255, 0.25) !important;
}

.titlebar-button{
  background-color: transparent !important;
  -moz-context-properties: stroke !important;
  stroke: currentColor !important;
}
.titlebar-button:hover{ background-color: hsla(0,0%,100%,.32) !important }
.titlebar-close:hover{ background-color: hsl(355,86%,49%) !important }

.titlebar-close{ list-style-image: url(chrome://browser/skin/window-controls/close.svg) !important }
.titlebar-min{ list-style-image: url(chrome://browser/skin/window-controls/minimize.svg) !important }
.titlebar-max{ list-style-image: url(chrome://browser/skin/window-controls/maximize.svg) !important }
.titlebar-restore{ list-style-image: url(chrome://browser/skin/window-controls/restore.svg) !important }
```

**Comment by filips123** [comment]
I made some changes to the Firefox Vertical Tabs and now it seems to work fine. Basically, I removed all platform-specific styles from `userChrome.css` (because they are not needed with PWAsForFirefox) and added a few things for compatibility with PWAsForFirefox styles (to the bottom):

```css
#new-tab-button, #alltabs-button, tabs {
    display: none;
}

html[tabsmode] #site-info {
    display: flex !important;
}
```

Complete file is also available here: [userChrome.css](https://github.com/filips123/PWAsForFirefox/files/9540016/userChrome.css.txt)
(you just need to rename it back to `.css` as GitHub does not support uploading CSS files)

Then, enable "Show browser tabs and enable using multiple tabs of the same web app" in the web app settings, and install and configure Tab Center Reborn as described in the theme's readme.

![slika](https://user-images.githubusercontent.com/16626308/189478482-be764d7e-49ff-4456-b880-57ab4e054b43.png)

**Comment by Hazem42** [comment]
Thank you so much, I really really appreciate your effort, you're an amazing person.
It works great for the default profile, Is there a way to make it work for the other profiles?

**Comment by filips123** [comment]
You need to do this for each profile in `%APPDATA%\FirefoxPWA\profiles`.

**Comment by Hazem42** [comment]
oh right, I was looking in the wrong place.
Again I really appreciate your time and effort man, Thank you so much <3
