### ISSUE TITLE
Support self-certified SSL certificate website

### ISSUE THREAD

**Issue by huang3303** [filips123/PWAsForFirefox#241]
Some self-hosted website services use self-certified SSL, like Nextcloud, FreshRSS.

**Comment by filips123** [comment]
I don't know exactly how to do this properly...

Simply adding [`danger_accept_invalid_certs`](https://docs.rs/reqwest/latest/reqwest/blocking/struct.ClientBuilder.html#method.danger_accept_invalid_certs) to requests would be a bad idea, as then all invalid certs would be accepted, which is a security risk. And some interactive prompt (like in browsers) is hard to implement because the native client is a separate program that cannot support much interaction.

An explicit flag that lets users disable cert verification should be easier to add, but it still isn't that secure because users cannot know what cert the website uses. Maybe it could be a command-line-only feature, so it appears more "advanced" and users don't mistakenly enable it without knowing the consequences.

**Comment by filips123** [comment]
In the next release, there will be `--tls-danger-accept-invalid-certs` and `--tls-danger-accept-invalid-hostnames` command-lin-only arguments for `site install` that let you disable certificate and hostname verification. There will also be `tls-root-certificates-der` and `tls-root-certificates-pem` that let you load custom root ceritificates as a more secure way to handle self-signed websites.
