### ISSUE TITLE
Release zipped version

### ISSUE THREAD

**Issue by xmha97** [filips123/PWAsForFirefox#255]
Please add the zipped version of PWAsForFirefox
![image](https://user-images.githubusercontent.com/23485114/207208090-94c287b3-536f-4248-bf01-c8269aca60b5.png)

**Comment by filips123** [comment]
The problem with zipped version is that Firefox would not detect its background messaging manifest (because it has to be in specific location with specific registry key) and that start menu entries and other OS integration still wouldn't be portable. The current recommended way to have portable-ish web apps is still to set  `FFPWA_USERDATA` environment variable.

However, I have some ideas on how to implement PortableApps.com packaging, including proper portable OS integration (specifically, installing web apps to the PortableApps.com app menu), but I'm not sure when it will be ready.
