### ISSUE TITLE
Make update notification less intrusive

### ISSUE THREAD

**Issue by MicaelJarniac** [filips123/PWAsForFirefox#258]
I am on Manjaro KDE, and I manage the binary with my other packages. Sometimes, there'll be an update, and I might take a day to apply it.

One thing that recently happened was that I was watching something on Netflix full screen while eating, and all of a sudden the update notification tab opened by itself, closed my Netflix, switched to that tab, and I had my hands busy, not being able to close it and go back to Netflix.

I'd rather have a simpler, or perhaps more delayed, update notification.

Popping up a new tab and immediately switching to it feels too intrusive and can cause a lot of trouble.

**Comment by MicaelJarniac** [comment]
I just disabled "show a popup on extension updates", I hope this disables this notification I talked about.

**Comment by filips123** [comment]
Yes, "show a popup on extension updates" should disable that notification.

The reason why that popup exists is to notify users who don't use package managers for updating the binary that the update is available and they should apply it. But maybe I can try to create an actual browser notification instead of immediately switching to a new tab, which should be less intrusive.
