### ISSUE TITLE
Installation of Google Translate as PWA prompts an error

### ISSUE THREAD

**Issue by Patricek0056** [filips123/PWAsForFirefox#275]
### Description
Installation of Google Translate PWA prompts an error. Or the error won't prompt, but the installation time would be infinite.
Code of error is: “Failed to parse web app manifest: invalid MIME: invalid token, '*' at position 6 at line 1 column 208”

### Steps to Reproduce
1. Go to https://translate.google.com/
2. Try to install this site as PWA
3. Error will prompt.

### Additional Information
(Nothing)

### Affected Websites
https://translate.google.com/

### Environment
* Operating system: Windows 11 22621.1192
* System architecture: 64-bit
* Desktop environment: (Nothing)
* Installation method: MSI
* PWAsForFirefox extension version: 2.4.0
* PWAsForFirefox native version: 2.4.0
* Firefox version: v109.0 (64-bit)

**Comment by filips123** [comment]
For some reason, Google Translate sets the icon's MIME type to `image/*` in the web app manifest. Because the manifest parser uses [hyperium/mime](https://github.com/hyperium/mime), which does not allow MIME patterns/ranges by default, the parsing will fail and result in that error.

As a workaround, you can install Google Translate if you uncheck "Use the manifest for determining app properties". I'll check if I can also allow MIME patterns in the parser.
