### ISSUE TITLE
Show the extension info at the bottom of settings section

### ISSUE THREAD

**Issue by Patricek0056** [filips123/PWAsForFirefox#276]
### Problem Description
The extension info is not in the bottom of the setting section, but it is only in `about:addons`.

### Proposed Solution
Show “PWAs For Firefox” version number, version number of native version, installation method, homepage, and author in the bottom of settings section (I think settings section under the gear button in “PWAs For Firefox” menu).

### Additional Information
(Nothing)

**Comment by filips123** [comment]
I will add version info (extension, native connector, runtime Firefox, main Firefox) and a few useful project links:

![slika](https://github.com/filips123/PWAsForFirefox/assets/16626308/ac9fee9e-fed4-47a2-9da5-fdb81a7ea88d)

Installation method, OS and DE won't be added because they can't be easily detected.
