### ISSUE TITLE
KDE Neon Unexpected Error occurred

### ISSUE THREAD

**Issue by StellarOrbit** [filips123/PWAsForFirefox#283]
### Description

Hello. I am running KDE Neon 22.04 and I am using the default Firefox install which is from deb and when I try to install the extension and program deb file, I cannot continue on. When I try to force it through command line to install runtime, it succeeds, but in the extension menu, it just flashes "unexpected error occurred".

### Steps to Reproduce

1. Go to install extension
2. Accept extension License
3. Click on install deb file
4. Steps do not continue to install runtime

### Affected Websites

* ...
* ...

### Environment

* Operating system: KDE Neon 22.04
* System architecture: x86_64
* Desktop environment: KDE
* Installation method: DEB
* PWAsForFirefox extension version: 2.4.0
* PWAsForFirefox native version: 2.4.0
* Firefox version: 109.0.1

**Comment by filips123** [comment]
At least for me, other extensions that use native messaging (Plasma Integration and KeePassXC) also do *not* work in a default Firefox. However, they *do* work with a version of Firefox downloaded directly from Mozilla (in a `.tar.bz2` archive).

Because of this, I think this could be a problem with KDE Neon's version of Firefox. You should probably report this bug to its developers. Unfortunately, I cannot do anything else, so I'll close this issue.
