### ISSUE TITLE
[PortableApps.com] Category

### ISSUE THREAD

**Issue by xmha97** [filips123/PWAsForFirefox#285]
I have feedback for the PortableApps.com version:

The categories are empty!
```
Category=
```

All categories must be the "Internet".
```
Category=Internet
```

![image](https://user-images.githubusercontent.com/23485114/216470923-c970b114-012a-4bab-9b79-1fc09fd9e428.png)

**Comment by filips123** [comment]
You can specify categories yourself when installing/editing web app in the extension (using the "categories" field). [Known categories](https://github.com/filips123/PWAsForFirefox/blob/main/native/src/integrations/categories.rs#L260-L279) are then mapped to the correct PortableApps.com category.

Some web apps already provide the correct category in their manifest. For others, there is no default, because I don't think a single category would fit different purposes of different web apps, but you can manually set it.
