### ISSUE TITLE
Failed to update web app manifest: Failed to parse web app manifest: expected value at line 1 column 1

### ISSUE THREAD

**Issue by UndarkAido** [filips123/PWAsForFirefox#315]
### Description
When I try to 'update web apps' I get

```
Failed to update web app manifest: Failed to parse web app manifest: expected value at line 1 column 1
```

### Steps to Reproduce

1. Go to the extension pop-up
2. Click on the settings cog
3. Click on 'Update web apps'

### Affected Websites

[firefoxpwa-stdout.log](https://github.com/filips123/PWAsForFirefox/files/11040488/firefoxpwa-stdout.log)
[firefoxpwa.log](https://github.com/filips123/PWAsForFirefox/files/11040486/firefoxpwa.log)
[firefoxpwa-stderr.log](https://github.com/filips123/PWAsForFirefox/files/11040487/firefoxpwa-stderr.log)

### Environment

* Operating system: Windows 11
* System architecture: 64-bit
* PWAsForFirefox extension version: 2.4.1
* PWAsForFirefox native version: 2.4.1
* Firefox version: 111.0.1 (64-bit)

**Comment by filips123** [comment]
@eudennis This happens because WhatsApp responds with some error page instead of the manifest when the request contains the `Referer` HTTP header set to the same URL as the request URL. This seems to be an error on their side and also happens when I try to reproduce the request with `curl`. Ironically, that header has been added to fix the installation of Facebook PWA...

As this seems to be a problem with WhatsApp, I probably cannot properly fix it. If WhatsApp has any bug report form, you can try to use it. As a workaround, you can uncheck "Use the manifest for determining app properties" and you should still be able to install the PWA.

**Comment by eudennis** [comment]
That very useful information, I will try that later and report back if I find anything useful. Thanks for the awesome response and patience!

**Comment by UndarkAido** [comment]
That worked, thank you so much!
