### ISSUE TITLE
Installation of some PWAs prompts an error

### ISSUE THREAD

**Issue by Patricek0056** [filips123/PWAsForFirefox#318]
### Description

I think, that they can't be installed with the “Use the manifest for determining app properties” option enabled.

Error message:
Failed to parse web app manifest: expected value at line 1 column 1

### Additional Information

Similar issue: https://github.com/filips123/PWAsForFirefox/issues/275

### Affected Websites

— https://apps.microsoft.com/
— https://www.messenger.com/

### Environment

* Operating system: Windows 11 22621.1485
* System architecture: 64-bit
* Installation method: MSI
* PWAsForFirefox extension version: 2.5.0
* PWAsForFirefox native version: 2.5.0
* Firefox version: 111.0.1

**Comment by filips123** [comment]
I can also reproduce this issue. I think it's similar to some problems with other sites (#315, #247), where websites respond with some random error page instead of the manifest when they see an unknown user agent. In this case, Microsoft responds with some HTML page for the "The request is blocked" error, and Messenger also with some HTML page that I haven't checked yet.

I'll check what I can do about this. In my opinion, websites shouldn't be doing this and it's completely their fault that they provide invalid manifests when they see unknown word in the user agent. I know such errors can be annoying, so I'll check if I can fix them, probably next week. Otherwise, I'll probably just create a list of known broken websites.

Also, sometimes I really don't understand some web developers. I try to be "responsible" by adding PWAsForFirefox to the user agent header, but considering it appears to cause so many problems, I might just remove it...

**Comment by filips123** [comment]
It seems requests made to crunchyroll.com from the native program are blocked by Cloudflare's protection page. What's interesting is that I tried doing basically the same request with curl, and it worked fine there, so maybe they're doing some more "advanced" detection that can differentiate between reqwest (HTTP client that PWAsForFirefox uses) and some other clients.

Because of this, this probably can't be fixed unless the website changes their detection algorithm.

You can try to disable "Use the manifest for determining app properties" when installing the website. Then, you will'be able to install it. However, requests for icons will still hit the same protection page, so icon probably won't work, unless you set your own.

**Comment by ItsRogueRen** [comment]
> It seems requests made to crunchyroll.com from the native program are blocked by Cloudflare's protection page. What's interesting is that I tried doing basically the same request with curl, and it worked fine there, so maybe they're doing some more "advanced" detection that can differentiate between reqwest (HTTP client that PWAsForFirefox uses) and some other clients.
> 
> Because of this, this probably can't be fixed unless the website changes their detection algorithm.
> 
> You can try to disable "Use the manifest for determining app properties" when installing the website. Then, you will'be able to install it. However, requests for icons will still hit the same protection page, so icon probably won't work, unless you set your own.

That's a suitable workaround then, what kind of images are supported for the icons when setting your own?

**Comment by filips123** [comment]
Most common formats are supported (such as PNG, JPG, ICO, GIF, SVG). It's recommended to be a square icon around 128x128 px in size, although this isn't strictly required. However, one requirement is that the icon should be on an accessible URL. So, the easiest way to get Crunchyroll icon would be to search if there is already any suitable icon available online. Maybe [this](https://seeklogo.com/images/C/crunchyroll-logo-ED92B45335-seeklogo.com.png) will be fine.
