### ISSUE TITLE
install and update PWAsForFirefox as a user on winget

### ISSUE THREAD

**Issue by candrapersada** [filips123/PWAsForFirefox#326]
why isn't there an option to install and update PWAsForFirefox as a user on winget?

**Comment by filips123** [comment]
It appears `winget` cannot detect that the installer is both per-user and per-machine. I will check if there is any way to fix this.

If you need to install PWAsForFirefox in a per-user mode using `winget`, you can currently run:

```sh
winget install --interactive firefoxpwa
```

And then manually select per-user option.

**Comment by filips123** [comment]
This has been fixed.

**Comment by filips123** [comment]
This has been reverted because `winget` does not work well with WiX-based installers in a user scope. This cannot be fixed until WiX or `winget` fixes this issues. More details are [here](https://github.com/microsoft/winget-pkgs/pull/107661#issuecomment-1556237704) and [here](https://github.com/microsoft/winget-cli/issues/3011).
