### ISSUE TITLE
Pinned webpage causes issue

### ISSUE THREAD

**Issue by Roterfux** [filips123/PWAsForFirefox#353]
I tried to create a pwa for Outlook.com, and I had the tab pinned.
If you try to create a PWA then, it causes "An unexpected error occurred".
It's hard to see if there is an error in the console, since it's flooded with errors from Outlook itself.

fyi: It works, if the tab is not pinned.

**Comment by filips123** [comment]
Does it work with other websites if they are pinned, and does it work with Outlook.com if it's not pinned? Because I've tested this with other websites and they work fine even if pinned, but when I tested it with Outlook.com, it didn't work even when it was unpinned.

I've checked the manifest for Outlook.com, and it seems it has malformed icon URLs (at least for some non-English variants), which PWAsForFirefox cannot process:
![slika](https://github.com/filips123/PWAsForFirefox/assets/16626308/e624511d-20c8-4e5e-98a4-b734c9ffcdb8)

This seems to be a problem with Outlook.com. However, I'll also try to improve error handling in cases of malformed URLs.

**Comment by Roterfux** [comment]
It does work for me, if Outlook is NOT pinned. (I do use it like this)

For testing, I tried to use https://roadmap.sh/ and https://dev.azure.com/.
Both work pinned as well.

**Comment by filips123** [comment]
Please create a `DEBUG` file as described [here](https://github.com/filips123/PWAsForFirefox/wiki/Troubleshooting). Then, try to install Outlook.com when pinned and upload `firefoxpwa.log`, `firefoxpwa-stdout.log` and `firefoxpwa-stderr.log`.

**Comment by Roterfux** [comment]
[firefoxpwa-stderr.log](https://github.com/filips123/PWAsForFirefox/files/11718628/firefoxpwa-stderr.log)
[firefoxpwa-stdout.log](https://github.com/filips123/PWAsForFirefox/files/11718629/firefoxpwa-stdout.log)
[firefoxpwa.log](https://github.com/filips123/PWAsForFirefox/files/11718630/firefoxpwa.log)

Console log
`Fehler beim Verarbeiten des Wertes für 'white-space'.  Deklaration ignoriert. 2 manage.html
GET
https://duerr5.bnapp02.kwp-online.de/relay/duerr5/pwa/bnapp/assets/icons/icon-72x72.png
[HTTP/3 200 OK 0ms]

GET
https://ssl.gstatic.com/docs/spreadsheets/favicon3.ico
[HTTP/3 200 OK 0ms]

GET
https://statics.teams.cdn.office.net/hashed/favicon/prod/favicon-f1722d9.ico
[HTTP/2 200 OK 0ms]

Fehler beim Verarbeiten des Wertes für 'white-space'.  Deklaration ignoriert. 2 install.html
XHRGET
https://outlook.office.com/mail/manifests/pwa.json?culture=de
[HTTP/3 200 OK 73ms]

Uncaught (in promise) Error: An unexpected error occurred undefined
`

**Comment by Roterfux** [comment]
That is how I did it. Unpin, install and pin again (or used the installed version) as a workaround.
Just noticed that as a weird behaviour

**Comment by filips123** [comment]
Perhaps Outlook.com is doing some testing by serving different manifests, and one of them is corrupted.

So, as this seems to be an issue with website and library (reqwest) that I cannot fix, I'll close this issue. Probably Microsoft will fix at some point, and I also hope reqwest fill fix that bug in the future.

I may also add this to the documentation when I finish it.

**Comment by Roterfux** [comment]
Ok
