### ISSUE TITLE
The extension doesn't recognize the native app!

### ISSUE THREAD

**Issue by xmha97** [filips123/PWAsForFirefox#356]
I've been using FirefoxPWA on Linux and Windows since 2021 and never had this problem, but today after installing Ubuntu, I noticed that the extension doesn't recognize the native app!

![Screenshot from 2023-06-09 15-54-46](https://github.com/filips123/PWAsForFirefox/assets/23485114/0235f6da-d8de-405b-9c75-9358584f25b6)

I created another profile on Firefox before installing FirefoxPWA, maybe that's causing the problem.

![Screenshot from 2023-06-09 16-15-31](https://github.com/filips123/PWAsForFirefox/assets/23485114/4f0c22cb-6182-49b2-8912-6373e7d4678b)

**Comment by filips123** [comment]
There are some problems with Firefox from Snap. Possible solutions are [here](https://github.com/filips123/PWAsForFirefox/issues/325#issuecomment-1564131231).

**Comment by xmha97** [comment]
Yes, my Firefox installed from Snap.
You can close this issue because I think that's the problem.

**Comment by xmha97** [comment]
Do you have any plans to turn the extension into a standalone app for managing PWAs without a browser?
Like Chrome App Launcher on older versions of Chrome:
![chrome-app-launcher.jpg](https://github.com/filips123/PWAsForFirefox/assets/23485114/158c57a5-665f-4dcc-bda2-fd3986be514a)

**Comment by filips123** [comment]
> Do you have any plans to turn the extension into a standalone app for managing PWAs without a browser?
Like "Chrome App Launcher" on older versions of Chrome:

No, because it would take too much effort (creating desktop apps can be a lot harder than just CLI programs) for not much additional benefit (as everything can already be done from the extension). However, if somebody else decides to build an alternative frontend/UI for PWAsForFirefox, then can do it and integrate it using [`firefoxpwa-connector`](https://github.com/filips123/PWAsForFirefox/discussions/352#discussioncomment-6079660).
