### ISSUE TITLE
Persistent terminal window on opening shortcut tasks

### ISSUE THREAD

**Issue by rknx** [filips123/PWAsForFirefox#370]
### Description

Opening task shortcuts leaves an open terminal window, which has to be manually closed. No errors.

### Steps to Reproduce

1. Pin outlook OWA to taskbar. Here's the manifest that I used for generating PWA: https://outlook.office.com/mail/manifests/pwa.json?culture=en
2. Right click on taskbar entry, and click any "tasks" (see image below).

### Additional Information

Task shortcuts screenshot:
![Task shortcut image](https://github.com/filips123/PWAsForFirefox/assets/7634068/4bcd580e-dfea-423d-8f6d-97d98afc75e1)

Open terminal screenshot:
![Terminal window image](https://github.com/filips123/PWAsForFirefox/assets/7634068/c8f6206d-12ca-4f58-9042-b463c97a1475)

`stderr` and `stdout` files were empty.

### Affected Websites

* outlook.office.com

### Environment

* Operating system: Windows 11 pro 10.0.25393 b25393
* System architecture: 64-bit
* Installation method: MSI
* PWAsForFirefox extension version: 2.7.1
* PWAsForFirefox native version: 2.6.2
* PWAsForFirefox runtime version: 2.6.2
* Firefox version: 115.0.2

**Comment by filips123** [comment]
Does it only happen when launching shortcuts, or also for normal web app launching? I assume the problem could be that the program is launched inside the new Windows Terminal instead of classic Conhost, and that unlike Conhost, Windows Terminal does not automatically close the window after the program stops. However, I don't know why this would only happen for shortcuts and not for normal launching. Maybe I forgot some setting that hides terminal when launching shortcuts.

**Comment by filips123** [comment]
I checked and the same properties regaring showing terminal are set both for the main and additional shortcuts, so it's probably that some weird thing that Windows is doing when launching additional shortcuts. I'll try to debug this better next week.

**Comment by rknx** [comment]
Changing "Profile termination behavior" to "Automatic" fixed the issue for me. Thank you. 

I also upvoted the feedback. Hopefully, they will change the default behavior in windows terminal.
