### ISSUE TITLE
Firefox Multi-Account Containers doesn't work INSIDE PWA profile

### ISSUE THREAD

**Issue by www-wagner** [filips123/PWAsForFirefox#375]
The _Firefox Multi-Account Container_ (FMAC) extension doesn't work **inside** the PWA profile. What I'm trying to do **isn't related** to #135.

### Steps to Reproduce

1. Create any web app using the extension using the default (or another) profile
2. Open the app (then the profile loads the app)
3. **Inside the profile**, install the FMAC extension
4. Click the FMAC icon and try to open the web app using another container
5. Nothing happens

### Additional Information

I know I could create multiple profiles to host every single app I created trough Firefox PWA extension. But I would like to try another approach: using only one profile (default or another) and put every app in a FMAC container.

For example, using FMAC I could put all Google related apps in a exclusive container, Meta related apps in another container and so on, everything using a single profile.

### Affected Websites

* ...
* ...

### Environment

* Operating system: Arch Linux
* System architecture: x64
* Desktop environment: KDE
* Installation method: AUR
* PWAsForFirefox extension version: 2.7.2
* PWAsForFirefox native version: 2.7.2
* PWAsForFirefox runtime version: 115.0.3
* Firefox version: 115.0.2

**Comment by filips123** [comment]
This will be fixed in the next version.

However, there are still a few problems. When the links target is set to new windows, opening a website with the assigned default container will immediately close the initial window and open a new one with the correct container. Additionally, some widgets will not work in this new window. Because of this, it is recommended not to use links target set to new windows and assign a default container at the same time. I will probably fix this in the future. I created #399 about this.

Additionally, when the tabs mode is disabled, there is no indicator for the current container. This will probably also be improved in the future.
