### ISSUE TITLE
Add a share button/copy link to clipboard action to the context menu

### ISSUE THREAD

**Issue by TheOneRing** [filips123/PWAsForFirefox#382]
### Problem Description

Using pwa's I don't have navigation bar and this no way to access the url to the current page/video.

### Proposed Solution

Add a share button to the window decorations and/or a context menu action that allows coping the current url.

**Comment by filips123** [comment]
There is already a custom copy link widget available. You can go to the customize page (Menu -> More tools -> Customize toolbar) and drag the copy link widget to your titlebar. Because of this, I'm not sure if context menu action is really needed.

**Comment by TheOneRing** [comment]
Uh you are right. I wasn't aware of the widget (don't need it with vanilla) and I didn't realize the pwa toolbar behaves that way. 😍 
It could make sense to make the button available by default but I'm happy with the current solution.
Thx.
Feel free to close.

**Comment by filips123** [comment]
It's not enabled by default because I prefer having only really necessary widgets enabled by default, as otherwise, the toolbar might look too bloated. Also, in case you are interested, there are [additional extra widgets](https://pwasforfirefox.filips.si/user-guide/browser/#additional-toolbar-widgets) available, if you want to use other functionalities that are otherwise similarly inaccessible in PWAs.
