### ISSUE TITLE
Extension not communicating with the firefoxpwa/Installation not sucesseful

### ISSUE THREAD

**Issue by syntz-dev** [filips123/PWAsForFirefox#400]
### Description

The extension is simply not communicating with the firefoxpwa.exe app. I already try to reinstall runtime, firefoxpwa.exe, the extension itself, but nothing works. "An unexpected error occurred" appears in the extension tab. And when I try to reinstall the firefoxpwa.exe, it doesn't go to the next step after the installation.

### Additional Information

I checked the console log of the extension and the error "Error: An unexpected error occurred install.30313083.js:1:3138" appears in it.
"An unexpected error occurred" is show whenever I try to make something in the extension tab.

### Environment

* Operating system: Windows 11 Pro Insider Preview Version 22H2 Build 23550.1000
* System architecture: x64
* Installation method: Both via chocolatey and MSI doesn't work
* PWAsForFirefox extension version: 2.7.3
* PWAsForFirefox native version: 2.7.3
* PWAsForFirefox runtime version: 2.7.3
* Firefox version: 117.0.1

**Comment by filips123** [comment]
Please follow [troubleshooting tasks](https://pwasforfirefox.filips.si/help/troubleshooting/#obtaining-native-logs) to get native and extension logs.

**Comment by alphazero-dev** [comment]
> Please follow [troubleshooting tasks](https://pwasforfirefox.filips.si/help/troubleshooting/#obtaining-native-logs) to get native logs.

I tried to do that, but it didn't gave me the firefoxpwa-stdout.log neither the firefoxpwa-stderr.log


The only thing I have is the firefoxpwa.log
[firefoxpwa.log](https://github.com/filips123/PWAsForFirefox/files/12751767/firefoxpwa.log)

**Comment by filips123** [comment]
One error that I can see in the log is that you tried to use a local path for the icon. This is currently not possible and you will have to use icon from URL (see #279 for details).

However, it doesn't show any details why the extension wouldn't work. Because the other two log files didn't appear, it's possible that the extension couldn't even connect to the native program and launch it. To check this, you can delete `firefoxpwa.log`, again try to use the extension, and check if any log files appear.

If this is the case, maybe you had a per-user installation of PWAsForFirefox that was later changed to per-machine installation, but some registry keys were left over, or the opposite. First check if more PWAsForFirefox installations are listed in the control panel or system settings. Then, check  theregistry (with regedit) if you have `firefoxpwa` key in `HKEY_CURRENT_USER\SOFTWARE\Mozilla\NativeMessagingHosts` and `HKEY_LOCAL_MACHINE\SOFTWARE\Mozilla\NativeMessagingHosts`.

**Comment by filips123** [comment]
Were you able to fix this issue? You can also try a few steps that I recently added to the previous comment.
