### ISSUE TITLE
Failed to parse web app manifest: invalid MIME: a slash (/) was missing

### ISSUE THREAD

**Issue by illtellyoulater** [filips123/PWAsForFirefox#405]
When trying to install website at https://dencode.com/ I get this error:

"Failed to parse web app manifest: invalid MIME: a slash (/) was missing between the type and subtype at line 1 column 288"

However, being this just a simple web page, there is no manifest in: developer-tools > application > manifest, or at https://dencode.com/manifest.json, so I don't understand where is the extension detecting the error?

I think I read there is a way to disable manifest parsing while installing websites, but I couldn't find an option for that... so I don't know how to fix this.

Could anyone guide me to a solution?

**Comment by filips123** [comment]
This happens because the website specifies the icon type as `x-icon`, which is (probably) an invalid MIME type.

> I think I read there is a way to disable manifest parsing while installing websites, but I couldn't find an option for that... so I don't know how to fix this.

You cannot disable manifest parsing, because the website doesn't even have manifest and this error happens in the '<link rel="icon">` HTML tag.

> Could anyone guide me to a solution?

One workaround is if you open developer tools and manually edit every `<link>` tag with `type="x-icon"` to `type="image/x-icon"` before installing the website.

I don't know yet how to properly solve this.

**Comment by filips123** [comment]
I added a basic workaround for this in 2.9.0. It should become available soon.

**Comment by executed** [comment]
This is what I get after updating everything to the latest version.
`Failed to parse web app manifest: Provided URL (https://blabla.net/) is not within the scope (https://blabla.net/vikunja/)`.

When searching app's HTML I couldn't find "x-icon" attributes.

**Comment by filips123** [comment]
That seems unrelated to this issue, and is probably a website issue. Please create a new issue and provide a full website URL.

**Comment by jumanji481** [comment]
I solved it by installing another website and changing app's url to what i needed :D
