### ISSUE TITLE
Install PWA Apps for all users (Per-Machine)

### ISSUE THREAD

**Issue by xmha97** [filips123/PWAsForFirefox#41]
Hi,
Please add a feature to install PWA apps for all users (per-machine)

**Comment by filips123** [comment]
Do you want to have the same PWA profile for all users or a separate profile for each?

The problem with installing PWAs per machine is that the data directory would need to be writable by all users (which could be bad for security) or some elevation prompt would be needed each time you want to make changes. I'm also not sure if a custom/portable Firefox installation can handle updates in a non-writable directory. I might check this in the future, and add support for global PWAs.

---

For now, if you want to have global PWAs with a global profile, you will need to compile the project from the source and set `FFPWA_USERDATA` build-time environment variable to some global directory where you want PWAs and other data to be installed. You will also need to make that path writable by all users. For more details about available environment variables, you can check [the source code](https://github.com/filips123/FirefoxPWA/blob/main/native/src/directories.rs#L24-L67).

---

If you want separate profiles, this could be a bit harder and I'm not sure if it works. Instead of setting `FFPWA_USERDATA`, you could try changing `userdata` to `sysdata` in the following lines:

* https://github.com/filips123/FirefoxPWA/blob/main/native/src/components/runtime.rs#L74 (this should install Firefox runtime into a global directory)
* https://github.com/filips123/FirefoxPWA/blob/main/native/src/storage.rs#L24
* https://github.com/filips123/FirefoxPWA/blob/main/native/src/storage.rs#L35 (to change where configuration file is stored)
* https://github.com/filips123/FirefoxPWA/blob/main/native/src/integrations/windows.rs#L72
* https://github.com/filips123/FirefoxPWA/blob/main/native/src/integrations/windows.rs#L294
* https://github.com/filips123/FirefoxPWA/blob/main/native/src/integrations/windows.rs#L323 (to change where PWA icons are stored)

I think this will still display all profiles are global, but each user will have own version of them. But I haven't tested it and unfortunately I'm not sure if it works.

**Comment by xmha97** [comment]
I want to install a PWA for all users with a separate profile for each.
I just want the icon (shortcut) to be created for all users.
For example, I install the PWA version of Twitter and different users can log in to their accounts.
I do not want multiple shortcuts to be created for one PWA.

**Comment by PeterCxy** [comment]
On Linux this could be doable by requesting root privileges via Polkit. Such a feature will be inherently very platform-dependent and require very different implementations on different OSes.

**Comment by markcellus** [comment]
I like the idea but it seems like there would be a lot of different use cases to deal with that may further complicate such a feature. Consider this scenario:

1. User A installs PWA once, which installs it for User B and C
2. User B uses PWA (changes settings, etc)
3. User C uses PWA (changes settings, etc)
3. User A uninstalls PWA

In this scenario would User B and C be okay logging in, only to find their nice PWA and settings were removed?
