### ISSUE TITLE
reopening a PWA after closing all windows opens new tab page

### ISSUE THREAD

**Issue by TitanNano** [filips123/PWAsForFirefox#42]
### Steps to Reproduce

1. Open a PWA
2. close all windows of the application
3. click on the dock icon of the PWA

### Expected Behavior
A new window of the PWA is opened.

### Actual Behavior
A new window with the Firefox new tab / home page is opened. There is also no way to get into the PWA anymore and the app has to be closed and restarted.

### Environment

* Operating system: macOS
* System architecture: x64
* Installation method: from source

* Firefox version: 90.0.2
* FirefoxPWA extension version: 0.5.0
* FirefoxPWA native version: 0.5.0

**Comment by dithom** [comment]
Same here, a fix would be awesome!

**Comment by DabeDotCom** [comment]
I don't know how hard it would be to roll into a proper "fix", but my naïve† workaround was to update the `browser.startup.homepage` setting in `about:config` to be the same as the `start_url` page of the PWA:

1. Open the app's Preferences (e.g., `⌘ Comma` on a Mac)
2. While the Preferences page is displayed, open "Developer Tools » Console" (`⌘⌥ K`)
3. In the console, type: `document.location.href="about:config"` and hit Enter
4. Accept the Risk
5. Type `home` into the Search Box, then change the value of the `browser.startup.homepage` field from `about:home` to the URL of your PWA and hit Enter

*Et voilà!*  Close the window/tab (`⌘ W`) and re-open a new one (`⌘ N` or `⌘ T`) and it should launch your app from now on, rather than showing the Firefox "about:home" page...

† PS — It goes without saying, of course, that this is all likely ***unsupported***: YMMV; use at your own risk; void where prohibited; not applicable in New Hampshire; etc.  ;-D

**Comment by filips123** [comment]
Well, at least that workaround is better than nothing. I will try to check how Firefox handles this internally, but if I don't find anything easy and useful, I will just implement setting homepage URL when you launch a PWA.

**Comment by filips123** [comment]
I implemented a fix/workaround for this which will be released in 2.0.0. However, it still doesn't work when multiple PWAs are in the same profile. This does not matter currently as multiple PWAs per profile should not be used because of #81, but once it is fixed, this also needs to be reworked.
