### ISSUE TITLE
Fail to load profile, if ~/.local/share/firefoxpwa/profiles is a symlink

### ISSUE THREAD

**Issue by alexjp** [filips123/PWAsForFirefox#426]
### Description

Error loading profile, when the profile is under a symlink.
In my case... since firefoxpwa has important data, I have tried to use a dotfile manager like stow which symlinks the ~/.local/share/firefoxpwa folder. (in my specific case, chezmoi, but the behaviour is the same).

Strangely, if the $HOME/.local/share/firefoxpwa/profiles folder is symlink, it fails to load the profile. (~/.local/share/firefoxpwa/runtime can be a symlink with no issues, it seems).

### Steps to Reproduce

1. Create a firefoxpwa profile
2. Check that it is working properly
3. Move it to another place, or rename it. Link that folder (ln -s) into ~/.local/share/firefoxpwa/profiles
4. See error -> try to launch profile and see error :)

### Additional Information

If I unlink the profiles folder and put it in its proper place, it launches with no issues, so the profile is fine.

### Affected Websites

Seems unrelated to specific websites

### Environment

* Operating system: Linux
* System architecture: x86-64
* Desktop environment: KDE
* Installation method: Archlinux packages
* PWAsForFirefox extension version: 2.9.0
* PWAsForFirefox native version: 2.9.0
* PWAsForFirefox runtime version: 2.9.0
* Firefox version: 120

Thanks for the awesome extension. As I use it more and more, I for sure want it backed up and in sync with my other machines

**Comment by filips123** [comment]
It works fine for me, at least on Ubuntu. What error do you get?

**Comment by alexjp** [comment]
> It works fine for me, at least on Ubuntu. What error do you get?

I get a text with "Failed to load the PWAsForFirefox configuration file."

(seems I shouldn't do a career on software testing, I keep doing incomplete tests !!! :) sorry!)

I just tested with a "quick symlink" and also worked. I then noticed the issue: in the previous non working case, the symlink "target" was on another disk.

So, in my case, this does not work:

~/.local/share/firefoxpwa> readlink profiles
/mnt/local/persist/home/alex/profiles_main


meaning a `profiles` symlink that links into `/mnt/local/persist/home/alex/profiles_main` which is on another disk.

Sorry...  I keep hitting on these edge cases. Anyway, I devised an alternative through rsync, in case it is not "fixable".

**Comment by filips123** [comment]
I think I know what the problem is and why it worked for me before...

When you launch a web app, PWAsForFirefox's userchrome code will try to [read config file](https://github.com/filips123/PWAsForFirefox/blob/6f5b39234bfd77e78322d6ef28af5c09cfe5e340/native/userchrome/profile/chrome/pwa/boot.jsm#L22-L34), which is located two directories above the profile directory. However, when using a symlink, the profile directory will be set to the symlink target (so, for example, `/mnt/local/persist/home/alex/profiles_main`), and the program will try to read the config relative from there (in your case, `/mnt/local/persist/home/config.json`).

When I initially tested this, I just created another symlink in the same directory as the original, so everything worked fine. I now tested it with a symlink pointing to somewhere else, and it also failed.

If you can do this, you can probably solve this issue by modifying the directory structure of your symlink targets to something like this:

```
/mnt/local/persist/home/alex/firefoxpwa/
  - profiles/
  - config.json
```

And then symlink both `profiles/` and `config.json` in the normal `~/.local/share/firefoxpwa/` directory. (Symlinking `runtime` probably isn't needed as it doesn't contain any user data/configuration.)

I think there isn't any other way of detecting the profile directory when it is a symlink.

**Comment by alexjp** [comment]
thanks for finding a solution :) fixed it!  THANKS!
