### ISSUE TITLE
Add the RPM package to the Fedora 39 repository

### ISSUE THREAD

**Issue by Heus-Sueh** [filips123/PWAsForFirefox#430]
### Problem Description
having to download the rpm package externally and install it is a process that could be made easier if it were included in the official repository or in copr and the user could install the package directly from the store in gnome or KDE

### Proposed Solution
add to official repository or [copr](https://copr.fedorainfracloud.org)

**Comment by filips123** [comment]
I think PWAsForFirefox in official Fedora repositories wouldn't really work that well, because (most) packages in a stable repository can't be updated (except with bugfixes), so the PWAsForFirefox package would quickly become outdated and potentially incompatible with the extension, which would still be updated regularly. It appears some packages can have exceptions to this update policy, but I don't know which packages can apply for this exception and how. The same problem is for most other official repos for other stable distros.

For Copr, it could probably work, because I think the updates can be submitted at any time. However, is there really an advantage compared to the already existing [packagecloud](https://packagecloud.io/filips/FirefoxPWA) repository? The only difference seems to be that it's slightly harder to add a third-party repository than to add a Copr repository.

Also, do GNOME Software and KDE Discover display packages from Copr even if that specific Copr repository isn't enabled? If this is the case, Copr might be useful, but otherwise, there is mostly still the same problem as with other third-party repositories that packages are not so discoverable.

**Comment by filips123** [comment]
I will close this because I think it doesn't provide any big advantage compared to the existing repository, and may also complicate the release process.
