### ISSUE TITLE
Forced open link confirmation popup

### ISSUE THREAD

**Issue by Zetaphor** [filips123/PWAsForFirefox#435]
### Description

Before a recent update, clicking a link in a PWA would open the link in my default browser (Firefox) as configured in my settings:

![image](https://github.com/filips123/PWAsForFirefox/assets/3112763/bf82d5cd-f0b0-497c-84bc-a640d19ff6b9)

Now whenever I click a link I get this dialog:

![image](https://github.com/filips123/PWAsForFirefox/assets/3112763/5573776d-bdc7-48e4-8191-dd6bf9f0bf97)

And am then forced to wait 3 seconds for the open button to become enabled.

This means for every link I need to click the link, wait 3 seconds, and then click a dialog box. I understand the intention, but this option should be something the user can disable, as it breaks workflows.

### Steps to Reproduce

1. Install Discord PWA
2. Click link
3. See dialog box that forces you to wait before opening the link or interacting with the PWA

### Affected Websites

All websites

### Environment

* Operating system: Fedora 39
* System architecture: x64
* Desktop environment: KDE 5.27
* Installation method: RPM
* PWAsForFirefox extension version: 2.91
* PWAsForFirefox native version: 2.91
* PWAsForFirefox runtime version: 121.0
* Firefox version: 120.0.1

**Comment by markcellus** [comment]
Yeah same here. I was wondering if this is a recent OS level dialog and not specific to this codebase. But you're using Fedora and I'm using Ubuntu and getting same error, so doesn't appear to be an OS-specific issue.

**Comment by filips123** [comment]
This is a change in Firefox 121, which was made to fix security vulnerability CVE-2023-6871. This was done [in this patch](https://hg.mozilla.org/mozilla-central/rev/89a118c5878608de9ce47ac8182b338e6ef13c33), but [the full bug report](https://bugzilla.mozilla.org/show_bug.cgi?id=1828334) is still private, so I don't know what exactly the issue was.

I don't know yet if this popup can be disabled specifically for default browser popups. I'll check how exactly the popup works and if it's possible to hide it when opening the default browser.

---

*Maybe unsafe workaround:*

You can also disable the popup **for all external protocols** by setting the `security.external_protocol_requires_permission` preference to `false`. However, this means that **any website will be able to automatically start any external protocol handler** ([details](https://searchfox.org/mozilla-central/source/modules/libpref/init/all.js#3954-3957]), which may again cause CVE-2023-6871 and other security issues.

I don't know what the latest vulnerability is about, but for example, another issue that was related to this preference a few years ago, was that opening a Zoom meeting link would automatically launch the Zoom client and join you into the meeting. Disabling this preference might again cause this behavior and other similar issues.

So, I would recommend you not to do this, but if you're aware of the risks, you can disable that preference. I hope I will be able to disable that popup specifically for opening a default browser in the future.

**Comment by MisakaImoutoWaifu** [comment]
Can confirm. I've also noticed some apps do not even open after confirming the link. Specifically a discord PWA I installed. Perhaps that is a different bug though.

**Comment by filips123** [comment]
@MisakaImoutoWaifu Do you mean that the links that you click do not open in a default browser, or that the whole PWA does not even start? Also, does this problem also happen when "open out-of-scope URLs in a default browser" is disabled?

**Comment by MisakaImoutoWaifu** [comment]
> @MisakaImoutoWaifu Do you mean that the links that you click do not open in a default browser, or that the whole PWA does not even start? Also, does this problem also happen when "open out-of-scope URLs in a default browser" is disabled?

It turned out at some point the default handler changed. It was set as Firefox, but a stale reference to it. Not sure what caused it, but I think it was unrelated to this issue.

**Comment by LSeelig** [comment]
> It turned out at some point the default handler changed. It was set as Firefox, but a stale reference to it.

How did you find this? I think I am having the same issue

**Comment by MisakaImoutoWaifu** [comment]
> > It turned out at some point the default handler changed. It was set as Firefox, but a stale reference to it.
> 
> How did you find this? I think I am having the same issue

Go to [about:preferences](about:preferences) and then scroll down to the "Applications" section. Change the "http" and "https" entries to your firefox binary.

**Comment by filips123** [comment]
This has been fixed in [2.10.0](https://github.com/filips123/PWAsForFirefox/releases/tag/v2.10.0). The confirmation popup will no longer be shown for HTTP(S) links. Once you update to the new version, you should probably re-enable `security.external_protocol_requires_permission`.

**Comment by PancakeTAS** [comment]
This issue seems to be back and the `security.external_protocol_requires_permission` workaround does not seem to work either. Both a temporary window and the popup are in the way now, clicking "Open Link" does not close to temporary window either.

![Image](https://github.com/user-attachments/assets/e36629b6-3170-472f-a57a-35711b0f43c1)

**Comment by filips123** [comment]
Yeah, I've fixed that again (#435) and it will be available in the next release.

**Comment by wKovacs** [comment]
The popup with the question is gone but the newly created tab stays open

Thx for the good work

**Comment by filips123** [comment]
Please check if this also happens in a fresh profile.

**Comment by matthugs** [comment]
I'm experiencing this same issue after my latest PWA runtime update. I've tried updating the protocol handlers for http/https in my PWA firefox profile, but it doesn't appear to change the behaviour when I click on a link, even after restarting the app.

<img width="1052" height="765" alt="screengrab of applications section of firefox about:preferences showing http and https handles set to an application called Feuerfawkes with the firefox logo icon" src="https://github.com/user-attachments/assets/b39adb09-a017-47b0-829d-a401c6a9aebb" />

(Note that my main firefox MacOS app is installed under a custom name; that weirdness may be enough to warrant a separate issue rather than attempting thread necromancy. Let me know!)

**Comment by drewjc75** [comment]
> (Note that my main firefox MacOS app is installed under a custom name; that weirdness may be enough to warrant a separate issue rather than attempting thread necromancy. Let me know!)

I just updated my Mac's FF to 146 and it immediately started doing the same thing, so I don't think it has anything to do with the funky naming scheme. My guess is that this has more to do with the Firefox version. The difference with me is that mine is set to "Use Firefox (default)" instead of the specific app. What's funny is that I tried to manually set it up by pointing it directly at Firefox.app in /Applications and it just reset itself to the default app.

EDIT: I just set it to manually open links using Chrome instead of Firefox—and now it's doing exactly the same thing, just asking "Open the https link with Google Chrome?" instead of "Open the https link with Firefox?"

**Comment by matthugs** [comment]
@drewjc75 sounds like an indication that the issue is with the Firefox runtime version being upgraded. (Mine has been, to 146. Has yours?)

**Comment by drewjc75** [comment]
> [@drewjc75](https://github.com/drewjc75) sounds like an indication that the issue is with the Firefox runtime version being upgraded. (Mine has been, to 146. Has yours?)

That's exactly what I was saying—I dunno about you, but when FF has an update I install it not only for the main app but also the PWAs. So I updated both, and immediately started getting that popup. I was only saying that I didn't think it had anything to do with your use of a custom name. 👍🏽

**Comment by jmadren** [comment]
Recently updated both Firefox and the PWA to 146.0 and now having the same issue. Just confirming that the issue seems to be with PWA, as I can open a link from any other app and don't get the confirmation window - it just opens as expected. Only links from the PWA are producing this.

**Comment by filips123** [comment]
Yeah, appearently something has changed in Firefox 146 that broke the code that hide the popup. I will try to fix this soon, you can follow #775 for this.
