### ISSUE TITLE
Linux aarch64 Support for Runtime installer?

### ISSUE THREAD

**Issue by tophneal** [filips123/PWAsForFirefox#450]
### Problem Description

I couldn't get the extension to recognize the symlink from /usr/bin/firefox to ./local/share/firefoxpwa/runtime/firefox and I came across the terminal option to install the runtime. I quickly learned Linux aarch64 is not supported.

### Proposed Solution

Add support for Linux aarch64 for CLI runtime installation.

### Additional Information

I unfortunately do not possess skills that could help with fulfilling this request through a PR :(

**Comment by filips123** [comment]
> I couldn't get the extension to recognize the symlink from /usr/bin/firefox to ./local/share/firefoxpwa/runtime/firefox

You need to copy the whole Firefox directory from `/usr/lib/firefox/` to `~/.local/share/firefoxpwa/runtime/`. Copying (or symlinking) just the main binary isn't enough. You also need to make sure that `~/.local/share/firefoxpwa/runtime/` is writeable by your user.

You can also use [FUSE OverlayFS](https://pwasforfirefox.filips.si/help/faq/#how-to-use-fuse-overlayfs-with-the-app-browser) to link the main Firefox instead of copying it.

Note that just symlinking the whole `/usr/lib/firefox/` directory probably won't work because PWAsForFirefox needs to add [a few custom files](https://github.com/filips123/PWAsForFirefox/tree/main/native/userchrome/runtime) to that directory.

> Add support for Linux aarch64 for CLI runtime installation.

Unfortunately, automatic runtime installation for Linux on ARM is not possible, as Mozilla does not provide official pre-built versions of Firefox for Linux on ARM.

**Comment by filips123** [comment]
I'll close this issue. Support for automatic runtime installation for Linux on ARM will be added if/when Mozilla provides official built Firefox for ARM.

If you have problems with manually setting up the runtime, please leave still let me know.
