### ISSUE TITLE
"Use the manifest for determining app properties" checkbox does not appear on the PWA installation page for Old Reddit

### ISSUE THREAD

**Issue by peldas** [filips123/PWAsForFirefox#485]
### Description

"Use the manifest for determining app properties" checkbox does not appear on the PWA installation page for Old Reddit so I cannot install a functioning version of it (the app installs but PWAsForFirefox does not recognise it as a valid app to open pass Old Reddit links to from my standard Firefox installation).

### Steps to Reproduce

1. Go to https://old.reddit.com/
2. Click the icon in the address bar
3. Try to find the "Use the manifest for determining app properties" checkbox at the bottom
4. It does not appear

### Additional Information

![image](https://github.com/filips123/PWAsForFirefox/assets/13115959/6647fd02-2783-48bc-b582-7b71d6a9e49f)

### Affected Websites

[Old Reddit](https://old.reddit.com/) (required due to #61 and #71).

### Environment

* Operating system: Windows 10 Home 22H2 19045.4291
* System architecture: x64
* Installation method: MSI (I believe)
* Extension version: 2.11.1
* Native version: 2.11.1
* Runtime version: 124.0.2
* Firefox version: 125.0

**Comment by filips123** [comment]
Old Reddit's manifest is also broken, as it specifies `https://www.reddit.com/` as scope and start URL. Because of that, the extension can't use it, so the checkbox is not displayed.

However, it appears that the latest Reddit redesign (the one at `https://www.reddit.com/`) now has a valid manifest. They "fixed" it by removing all shortcuts and most icons (and it seems they really want users to use their mobile app), but at least you should be able to install it. So, if you don't mind using the new design, you can try that.

I will try to make opening links work with websites without manifest in the future, but I think it will require quite a lot of changes, and I also don't have time currently, so it may take a while.

Also, summary of manifests of various Reddit "versions" and their issues:

* Manifest for `old.reddit.com`: https://www.redditstatic.com/desktop2x/img/favicon/manifest.json (not working, because of invalid shortcuts, scope and start URL)
* Manifest for `new.reddit.com` (the old "new" version): https://www.redditstatic.com/desktop2x/img/favicon/manifest.json?v=2 (seems to be the same file as above, also not working for the same reason)
* Manifest for `www.reddit.com`: (the latest version): https://www.redditstatic.com/shreddit/assets/favicon/manifest.json (working, but with all shortcuts removed)

**Comment by filips123** [comment]
I will close this issue because it's a problem with (old) Reddit that I can't fix. I've updated the documentation in ada421c139e2b12d968d8a4b64e52ba066a9486c to mention that only the old Reddit now has issues.

I will probably make opening links work with websites without manifest in the future, but I don't know when.
