### ISSUE TITLE
The .desktop entry generated with a non-standard "WebApps" category on Linux

### ISSUE THREAD

**Issue by Granitosaurus** [filips123/PWAsForFirefox#544]
### Description

Currently the .desktop file generated contains invalid `Categories` entry:

```
Categories=GTK;WebApps;
```

This can be identified by using `desktop-file-validate` tool which reports:

```
❯ : desktop-file-validate ~/.local/share/applications/FFPWA-xxx.desktop 
/home/myuser/.local/share/applications/FFPWA-xxx.desktop: error: value "GTK;WebApps;" for key "Categories" in group "Desktop Entry" contains an unregistered value "WebApps"; values extending the format should start with "X-"
````

**To fix this** replacing `WebApps` with `X-WebApps` does the trick.

See freedesktop docs on available standard categories: https://specifications.freedesktop.org/menu-spec/latest/category-registry.html 

Maybe `WebApp` should be replaced with standard `Network` category?

**Comment by Granitosaurus** [comment]
Seems like only 1 main category is allowed per desktop entry so using `Network` and user specified category (through extension, which is mandatory selection) is not allowed. So I think `X-WebApp` is best choice here or it should be removed entirely and only user's selection left there.

**Comment by filips123** [comment]
I think I've added `WebApps` category because it was created by the [Linux Mint's Webapp Manager](https://github.com/linuxmint/webapp-manager/commit/d4ce030741fc2e98dff48753a17b0a8bc027db59). However, now that I checked it again, it seems they only provide this category as an option, and it's not always added like in PWAsForFirefox.

So, I think it should just be removed entirely, so only `GTK` and user categories are left.
