### ISSUE TITLE
Firefox should be installed into Local instead of Roaming AppData

### ISSUE THREAD

**Issue by ite-klass** [filips123/PWAsForFirefox#549]
The Firefox installation should not be installed into Local AppData, NOT Roaming AppData.

```
%USERPROFILE%\AppData\Roaming\FirefoxPWA\
```

Although [Roaming is apparently no longer a thing in newer Windows versions](https://learn.microsoft.com/en-us/windows/apps/design/app-settings/store-and-retrieve-app-data#roaming-data), installing the Firefox installation into Roaming seems wrong, misleading, and confusing.

Reference docs:

* [Local AppData](https://learn.microsoft.com/en-us/windows/apps/design/app-settings/store-and-retrieve-app-data#local-app-data)
* [Roaming AppData](https://learn.microsoft.com/en-us/windows/apps/design/app-settings/store-and-retrieve-app-data#roaming-data)

> Local app data should be used for any information that needs to be preserved between app sessions and is not suitable for roaming app data. 

> Don't roam large sets of app data.

**Comment by filips123** [comment]
Runtime is installed to Roaming AppData because all directories in PWAsForFirefox are controlled by [three options](https://pwasforfirefox.filips.si/resources/installation-directories/), so all directories (including `runtime`), have to be in one of these directories. This makes code and documentation less complex and is more consistent across all operating systems...

Although I agree that Local AppData would probably be a more appropriate place to store runtime, I don't think it's worth changing it now, as that would introduce additional complexity to the code (new configuration variable, and probably also migrations from the old path), especially since roaming is no longer supported on Windows.

**Comment by ite-klass** [comment]
I see. Thank you for your reasoning. Feel free to close as won't-fix - dunno if you want to keep it open for other reasons/for reference.
