### ISSUE TITLE
[macOS] App opens to "about:blankhome" after closing window without quitting

### ISSUE THREAD

**Issue by tmercswims** [filips123/PWAsForFirefox#593]
### Description
On macOS, closing the last window of an application doesn't usually fully quit the application. This is also true for PWAs (since they're just Firefox), which seems to be causing an issue.

### Steps to Reproduce
1. Launch PWA while it isn't already running.
2. It opens to the start page just fine.
3. Close the window, but don't quit the app completely (no cmd+Q).
4. Open the app again.
5. It opens to the URL `about:blankhome`

### Additional Information
Demo:
https://github.com/user-attachments/assets/f94312a4-5cc7-4674-a60c-50b78e3860c7

App settings:
<img width="405" alt="image" src="https://github.com/user-attachments/assets/9f24b7a8-2b94-43f4-93b0-658f46458900"><img width="406" alt="image" src="https://github.com/user-attachments/assets/93d8ce65-e124-4833-a691-2308254aa72e">

Profile settings:
<img width="405" alt="image" src="https://github.com/user-attachments/assets/63d5b5ad-a8e4-408c-9dba-afd064a1f8b4">

Extension settings:
<img width="407" alt="image" src="https://github.com/user-attachments/assets/ae661b43-cc23-42bc-9784-c5855fb3c0a8">

App browser settings:
<img width="685" alt="image" src="https://github.com/user-attachments/assets/d278d01c-0de3-4f05-ad44-805de61fed86">

While recording this demo, I also noticed that this only seems to happen when I launch/reopen the app from the dock. If I attempt to launch it again directly (after closing the window but not quitting) a new instance of the app starts which never fully launches, just sits in the dock bouncing forever. This feels like a different problem, and to be honest I don't really care about it, personally, but if you want me to file a separate issue I'd be happy to.

I've played with the "When launching a web app that is already opened" setting, but it doesn't seem to make a difference.

I've tried completely removing the app and its profile and starting fresh, and this still happens.

Lastly, this is a somewhat new thing, but it didn't start recently enough that I could even guess at a first version of anything where it started. I apologize for this, I've dragged my feet opening an issue about it 😅

### Affected Websites
Affects the only app I have installed, Google Meet.

### Environment
* Operating system: macOS 15.1.1
* System architecture: ARM64
* Desktop environment: N/A
* Installation method: Homebrew
* PWAsForFirefox extension version: 2.13.1
* PWAsForFirefox native version: 2.13.1
* PWAsForFirefox runtime version: 132.0.2
* Firefox version: 133.0b9 (Developer Edition)

**Comment by pciao15** [comment]
I am also having this exact issue with the same OS, settings, and installation method. The only app I have installed is Google Messages in the hopes I could use it similar to a standard native messaging app (like WhatsApp or iMessage).

**Comment by Nickno95** [comment]
I am also having this issue. It is the PWA profile's home page.

Manually setting the browser home page to the website url inside the PWA fixes it for a while, but it eventually gets reset back to the about:blankhome.

It needs to default and maintain the website as the home page.

**Comment by tmercswims** [comment]
@Nickno95 Yep, I think you're absolutely right. I noticed that too, but it slipped my mind when I was writing this up. Setting the home page in the app browser's settings seems to stick until the next time that it's fully quit, at which point it gets reset back to empty.

**Comment by natediz** [comment]
Having the same issue, but here is my workaround: Add the "Home" button to the top bar (right click>customize toolbar). When the blank pages comes up, pressing the home button will reload to the real starting page. Alternatively, you can also create a new window/tab and close the first one. But hopefully it can get fixed.

**Comment by filips123** [comment]
Unfortunately, I currently can't test macOS support, as I can't make macOS VM work on my new system.

@TitanNano If you still have time, could you please check this, as you developed an initial macOS support?

**Comment by Nickno95** [comment]
From what I've gathered, manually setting the home page in the settings after the app is launched will set the browser.startup.homepage preference in the pwa profile's pref.js file:

 user_pref("browser.startup.homepage", "https://github.com");

This pref.js file and its browser.startup.homepage is overridden in the browser.jsm configureSettings() function (/native/userchrome/profile/chrome/pwa/content/browser.jsm).

Maybe this preference needs to be set to the pwa site in configureSettings function?

Another place it could be is either the handleOpeningNewWindow function (browser.jsm), which I think is called when the app first launches and is what is actually going to the pwa site (since the homepage pref is not even set).

Or the handleTabsMode function (browser.jsm), which looks like it might be handling opening a new tab. I think having the app 'running' but no active window and then opening it again is considered creating a new tab?

I don't know how to go about testing this though since I am not sure where the extension files are stored.
