### ISSUE TITLE
Support Apple Silicon natively

### ISSUE THREAD

**Issue by jvacek** [filips123/PWAsForFirefox#60]
### Problem Description
When using `firefoxpwa` on Apple Silicon, you get the Intel runtime instead of the native one.

### Proposed Solution

Switch case for the right runtime, and support the ARM one

### Additional Information

N/A

**Comment by filips123** [comment]
Do you know why FirefoxPWA doesn't use AS version and how to use it? Does it need some specific launch options?

**Comment by akdor1154** [comment]
Googling a bit - an binary running in Rosetta will launch child processes in Rosetta as well by default. You can apparently opt out by launching child proc as `arch -arm64 child_proc ...` (https://eclecticlight.co/2021/01/27/how-rosetta-complicates-call-chains-on-m1-macs/).
Haven't tested, I do have access to an M1 but it's not mine to go futzing around with all the time :)

**Comment by filips123** [comment]
In this case, it seems [`Runtime::run`](https://github.com/filips123/FirefoxPWA/blob/main/native/src/components/runtime.rs#L285-L298) needs to be modified to check if it is running in Rosetta and launch runtime with that `arch -arm64` command if needed. Unfortunately, I don't have access to Mac so I cannot test and develop this, and I don't want to mess with code I cannot test. However, I can merge PR if someone can provide it.

Also, in case FirefoxPWA was installed using Homebrew, shouldn't it be using a bottle for Apple Silicon and thus not launch any subprocesses in Rosetta?

**Comment by matteoturini** [comment]
I have an M1 MacBook Air to test if needed.

**Comment by filips123** [comment]
Thank you, that would be nice.

First, can you check if the PWA Firefox runtime is still using Rosetta, or has something changed since this issue was opened? You need to launch any PWA and then check if its Firefox process is running natively or using Rosetta. I think you can use activity monitor for this (check [this](https://forums.macrumors.com/threads/is-there-a-way-to-tell-if-youre-running-the-arm-native-version-of-an-app-or-if-its-using-rosetta.2270030/post-29280564) or [this](https://thenextweb.com/news/how-to-check-app-running-m1-native-version-on-mac)).

Then, please also check if the `firefoxpwa` binary is available in the ARM architecture using `file $(which firefoxpwa)`. And just in case, please also check if downloaded Firefox runtime is still Universal 2 binary using `file ~/Library/Application\ Support/firefoxpwa/runtime/Firefox.app/Contents/MacOS/firefox`.

**Comment by ChronoStriker1** [comment]
As no one answered you I can confirm on my Macbook M1 pro that the firefoxpwa installed from brew is using the arm version:
file $(which firefoxpwa)
/opt/homebrew/bin/firefoxpwa: Mach-O 64-bit executable arm64
and the downloaded firefox runtime is the Universal binary:
file ~/Library/Application\ Support/firefoxpwa/runtime/Firefox.app/Contents/MacOS/firefox
/Users/chronostriker1/Library/Application Support/firefoxpwa/runtime/Firefox.app/Contents/MacOS/firefox: Mach-O universal binary with 2 architectures: [x86_64:Mach-O 64-bit executable x86_64Mach-O 64-bit executable x86_64] [arm64:Mach-O 64-bit executable arm64Mach-O 64-bit executable arm64]
/Users/chronostriker1/Library/Application Support/firefoxpwa/runtime/Firefox.app/Contents/MacOS/firefox (for architecture x86_64):	Mach-O 64-bit executable x86_64

Just for the fun of it I attempted to remove the x86_64 portion with lipo and it is not launching

**Comment by filips123** [comment]
Shouldn't then Firefox launched by `firefoxpwa` run natively, without Rosetta? Because according to [this comment and article](https://github.com/filips123/PWAsForFirefox/issues/60#issuecomment-957051729), all child processes run on the same architecture.

**Comment by ChronoStriker1** [comment]
I would have thought so but it clearly isnt.

**Comment by ChronoStriker1** [comment]
Getting back to baseline redownloading the runtime and launching via the app icon, is running the x86_64 runtime.
I tested running the same command the loader is loading from the terminal and it's not launching whatsoever.

**Comment by filips123** [comment]
I don't know why this happens... Hopefully someone who knows more about macOS can help.

> I tested running the same command the loader is loading from the terminal and it's not launching whatsoever.

Is there any error? Also, can you please provide logs (create an empty `DEBUG` file inside `~/Library/Application Support/firefoxpwa` dir, run this command again and logs should be written to that directory)?

**Comment by ChronoStriker1** [comment]
No errors, and here is the [log[](url)](url
[firefoxpwa.log](https://github.com/filips123/PWAsForFirefox/files/8773028/firefoxpwa.log)
)

**Comment by ChronoStriker1** [comment]
And for completions sake here is a log when running from the extension in firefox (showing as apple in activity monitor, pwa while showing Intel in activity monitor does seem to launch)
[firefoxpwa.log](https://github.com/filips123/PWAsForFirefox/files/8773054/firefoxpwa.log)

and one from after I run lipo on the runtime and run from the extension firefox (showing as apple in activity monitor. pwa does not appear to launch)

**Comment by filips123** [comment]
Unfortunately, logs don't show anything useful and I don't know what else to try (at least for now).

**Comment by filips123** [comment]
I made some changes in 2.0.0 that may fix this issue. After updating to 2.0.1 (which should become available soon), run "Update web apps" from the extension settings to apply those changes. Then, check if web apps are now running natively. Also, please check what `file ~/Applications/NAME OF YOUR WEB APP.app/Contents/MacOS/loader` prints.

**Comment by ChronoStriker1** [comment]
That didnt seem to work.  The apps now don't run nor do they seem to create a log entry.  I have tried removing them and the two apps I made are both giving errors like this:
14:32:28 [INFO] Uninstalling the web app
14:32:28 [INFO] Uninstalling system integration
14:32:28 [ERROR] Failed to uninstall system integration

Caused by:
    0: Failed to remove application bundle
    1: Telegram Web.app is not a web app

**Comment by filips123** [comment]
Please enable debug mode (create a `DEBUG` file inside `~/Library/Application Support/firefoxpwa/`). Then, try to remove app again (from the extension) and check `firefoxpwa.log`. It should display why bundle was not detected as a web app.

Also check which architecture was `~/Applications/Telegram Web.app/Contents/MacOS/loader` built for (with `file` command) and what happens when you run it directly.

**Comment by ChronoStriker1** [comment]
`16:05:27 [INFO] Connection established: ["/opt/homebrew/opt/firefoxpwa/libexec/firefoxpwa-connector", "/Library/Application Support/Mozilla/NativeMessagingHosts/firefoxpwa.json", "firefoxpwa@filips.si"]
16:05:27 [INFO] Received a request: GetSystemVersions(GetSystemVersions)
16:05:27 [INFO] Processed the request: SystemVersions { firefoxpwa: Some("2.0.1"), firefox: Some("103.0.1"), _7zip: None }
16:05:27 [INFO] Sent a response
16:05:27 [INFO] Connection established: ["/opt/homebrew/opt/firefoxpwa/libexec/firefoxpwa-connector", "/Library/Application Support/Mozilla/NativeMessagingHosts/firefoxpwa.json", "firefoxpwa@filips.si"]
16:05:27 [INFO] Received a request: GetProfileList(GetProfileList)
16:05:27 [INFO] Processed the request: ProfileList({Ulid(0): Profile { ulid: Ulid(0), name: Some("Default"), description: Some("Default profile for all sites"), sites: [] }, Ulid(2006779846727024411914537792809154611): Profile { ulid: Ulid(2006779846727024411914537792809154611), name: Some("Telegram"), description: None, sites: [Ulid(2006779850991841650795291227246620905)] }})
16:05:27 [INFO] Sent a response
16:05:27 [INFO] Connection established: ["/opt/homebrew/opt/firefoxpwa/libexec/firefoxpwa-connector", "/Library/Application Support/Mozilla/NativeMessagingHosts/firefoxpwa.json", "firefoxpwa@filips.si"]
16:05:27 [INFO] Received a request: GetSiteList(GetSiteList)
16:05:27 [INFO] Processed the request: SiteList({Ulid(2006779850991841650795291227246620905): Site { ulid: Ulid(2006779850991841650795291227246620905), profile: Ulid(2006779846727024411914537792809154611), config: SiteConfig { name: None, description: None, start_url: None, document_url: Url { scheme: "https", cannot_be_a_base: false, username: "", password: None, host: Some(Domain("web.telegram.org")), port: None, path: "/z/", query: None, fragment: None }, manifest_url: Url { scheme: "https", cannot_be_a_base: false, username: "", password: None, host: Some(Domain("web.telegram.org")), port: None, path: "/z/site_apple.webmanifest", query: None, fragment: None }, categories: None, keywords: None, enabled_url_handlers: [], enabled_protocol_handlers: [], custom_protocol_handlers: [] }, manifest: WebAppManifest { start_url: Absolute(Url { scheme: "https", cannot_be_a_base: false, username: "", password: None, host: Some(Domain("web.telegram.org")), port: None, path: "/z/", query: None, fragment: None }), scope: Absolute(Url { scheme: "https", cannot_be_a_base: false, username: "", password: None, host: Some(Domain("web.telegram.org")), port: None, path: "/z/", query: None, fragment: None }), name: Some("Telegram Web"), short_name: Some("Telegram Web"), description: Some("Telegram is a cloud-based mobile and desktop messaging app with a focus on security and speed."), categories: [], keywords: [], dir: Auto, lang: None, display: Standalone, orientation: Any, background_color: Some(Color { r: 1.0, g: 1.0, b: 1.0, a: 1.0 }), theme_color: Some(Color { r: 1.0, g: 1.0, b: 1.0, a: 1.0 }), iarc_rating_id: None, prefer_related_applications: false, related_applications: [], protocol_handlers: [], shortcuts: [], share_target: None, icons: [IconResource { src: Absolute(Url { scheme: "https", cannot_be_a_base: false, username: "", password: None, host: Some(Domain("web.telegram.org")), port: None, path: "/z/icon-square-192x192.png", query: None, fragment: None }), type: Some("image/png"), sizes: {Fixed(192, 192)}, purpose: {Any}, label: None }, IconResource { src: Absolute(Url { scheme: "https", cannot_be_a_base: false, username: "", password: None, host: Some(Domain("web.telegram.org")), port: None, path: "/z/icon-square-384x384.png", query: None, fragment: None }), type: Some("image/png"), sizes: {Fixed(384, 384)}, purpose: {Any}, label: None }, IconResource { src: Absolute(Url { scheme: "https", cannot_be_a_base: false, username: "", password: None, host: Some(Domain("web.telegram.org")), port: None, path: "/z/icon-square-512x512.png", query: None, fragment: None }), type: Some("image/png"), sizes: {Fixed(512, 512)}, purpose: {Any}, label: None }], screenshots: [ScreenshotResource { src: Absolute(Url { scheme: "https", cannot_be_a_base: false, username: "", password: None, host: Some(Domain("web.telegram.org")), port: None, path: "/z/screenshot.jpg", query: None, fragment: None }), type: Some("image/jpeg"), sizes: {Fixed(1280, 802)}, platform: None, label: None }] } }})
16:05:27 [INFO] Sent a response
16:05:27 [INFO] Connection established: ["/opt/homebrew/opt/firefoxpwa/libexec/firefoxpwa-connector", "/Library/Application Support/Mozilla/NativeMessagingHosts/firefoxpwa.json", "firefoxpwa@filips.si"]
16:05:27 [INFO] Received a request: GetConfig(GetConfig)
16:05:27 [INFO] Processed the request: Config(Config { always_patch: false, runtime_enable_wayland: false, runtime_use_xinput2: false, runtime_use_portals: false })
16:05:27 [INFO] Sent a response
16:05:27 [INFO] Connection established: ["/opt/homebrew/opt/firefoxpwa/libexec/firefoxpwa-connector", "/Library/Application Support/Mozilla/NativeMessagingHosts/firefoxpwa.json", "firefoxpwa@filips.si"]
16:05:27 [INFO] Received a request: GetProfileList(GetProfileList)
16:05:27 [INFO] Processed the request: ProfileList({Ulid(0): Profile { ulid: Ulid(0), name: Some("Default"), description: Some("Default profile for all sites"), sites: [] }, Ulid(2006779846727024411914537792809154611): Profile { ulid: Ulid(2006779846727024411914537792809154611), name: Some("Telegram"), description: None, sites: [Ulid(2006779850991841650795291227246620905)] }})
16:05:27 [INFO] Sent a response
16:05:31 [INFO] Connection established: ["/opt/homebrew/opt/firefoxpwa/libexec/firefoxpwa-connector", "/Library/Application Support/Mozilla/NativeMessagingHosts/firefoxpwa.json", "firefoxpwa@filips.si"]
16:05:31 [INFO] Received a request: UninstallSite(UninstallSite { id: Ulid(2006779850991841650795291227246620905) })
16:05:31 [INFO] Uninstalling the web app
16:05:31 [INFO] Uninstalling system integration
16:05:31 [DEBUG] (1) firefoxpwa::integrations::implementation::macos: APPLFFPWA-01G9YY5DX2G59P7TD2M41RSW79 should contain 01G9YY5DX2G59P7TD2M41RSW79
16:05:31 [ERROR] Failed to process request

Caused by:
    0: Failed to uninstall system integration
    1: Failed to remove application bundle
    2: Telegram Web.app is not a web app
16:05:31 [INFO] Sent a response`

**Comment by filips123** [comment]
I fixed the problem with removing web apps in 2.0.2. I still don't know why you cannot launch web apps, but maybe #198 fixed it. After updating to 2.0.2, please update your web apps and try again.

**Comment by ChronoStriker1** [comment]
This release seems to work as expected.

**Comment by ChronoStriker1** [comment]
Yes it is using arm now

Aug 9, 2022 11:41:35 AM Filip Š ***@***.***>:

**Comment by filips123** [comment]
Ok, then I think this issue can be closed.
