### ISSUE TITLE
The generated SSB is completely blank 

### ISSUE THREAD

**Issue by Poundex** [filips123/PWAsForFirefox#600]
### Description

When launching the SSB after creating it in the extension the page it is supposed to wrap does not load, and everything is blank.

### Steps to Reproduce

1. Create SSB as normal with extension in main browser
2. Launch it

### Additional Information

It works fine on my laptop, but not my Pine Note. For the latter I had to use Firefox Nightly, as this is the only distribution that supplies non-package (simple archive) versions for aarch64 that PWAsForFirefox can use for its runtime. 

### Environment

* Operating system: Debian Trixie
* System architecture: aarch64
* Desktop environment: KDE Plasma 
* Installation method: Downloaded tarball from Mozilla Downloads
* PWAsForFirefox extension version: 2.13.1
* PWAsForFirefox native version: 2.13.1
* PWAsForFirefox runtime version: 135.0a1
* Firefox version: 135.0a1

**Console log:** [console-export-2024-12-19_14-15-36.txt](https://github.com/user-attachments/files/18199225/console-export-2024-12-19_14-15-36.txt)

**Screenshot:** ![Screenshot_20241219_142511](https://github.com/user-attachments/assets/6d84d5c7-374e-44f4-b004-6b7887448640)

**Comment by filips123** [comment]
Appearenly something has changed in Firefox Nightly that now breaks loading. I'll try to fix it soon.

**Comment by filips123** [comment]
This has been fixed in [2.13.2](https://github.com/filips123/PWAsForFirefox/releases/tag/v2.13.2).

As the extension hasn't been reviewed yet, you will have to manually download the new native program directly from GitHub or package managers. Please make sure to do this before Firefox 134 is released on 2025-01-07 to avoid problems. The extension will say it's outdated, but that's fine until the new extension version is also approved.

If you still have problems after updating to 2.13.2, make sure that the native version mentioned in the extension settings (About the project) is also 2.13.2. If it's not, uninstall the native program from the system settings and try again. If everything is updated to 2.13.2 but you still have problems, please run "Patch profiles and runtime" from the extension settings.

**Comment by executed** [comment]
I had problems.
My Firefox version was 134, native version was 2.13.1 and extension version still is 2.13.1.
After deleting native from Windows x64 and re-installing the extension to latest available (still 2.13.2) the problem is gone.

I'm regular user so I could imagine this issue might be happening to a lot of us.
Thank you everyone involved for your hard work!
