### ISSUE TITLE
Make urls open in new window

### ISSUE THREAD

**Issue by kbzowski** [filips123/PWAsForFirefox#94]
### Problem Description

I have tested Firefox PWA with Google chat - it works great. But the links sent in the chat opens in the same window as the app - which essentially leaves the app. Is it possible to make it open in system Firefox, or the default browser?

**Comment by filips123** [comment]
You can shift-click on a link to open it in a new window (but this will still be a PWA-styled window).

If you want to make this a default behavior, you can set "When opening a link that should normally open in a new window or tab"  to "Force links into a new window" in the settings page and restart the PWA. However, unfortunately, there is a bug that will reset this preference to default value every time you open the settings page, but I'll fix this in a future update.

If you want to open a link in default browser, you can right-click on a link and then choose "Open Link in Default Browser". I might also add some keyboard shortcut for this in the future.

You could also enable "Open out of scope URLs in a default browser" if you want to open all external links in default browser, but this is not recommended because it breaks some websites (most commonly websites with SSO, so probably also Google Chat).

**Comment by markcellus** [comment]
> You could also enable "Open out of scope URLs in a default browser" if you want to open all external links in default browser, but this is not recommended because it breaks some websites (most commonly websites with SSO, so probably also Google Chat).

This is what I've been doing. It won't break SSO if you add the domain of your SSO to the `firefoxpwa.allowedDomains` config as instructed in later comments inside #62. 

1. Open Google Chat PWA
2. Press F6 and then enter `about:config` in the popup
3. Search for `firefoxpwa.allowedDomains`
4. Add the domain(s) of your SSO
1. Enable "Open out of scope URLs in a default browser"

In your case, if you're using Google Chat with Google's normal sign in, it will redirect you to `accounts.google.com`, so that's the domain you'll need to add to step 4.

Hope this helps!

**Comment by markcellus** [comment]
> unfortunately, there is a bug that will reset this preference to default value every time you open the settings page, but I'll fix this in a future update.

@filips123 do you happen to know the issue number for this bug? So that I can follow along to know when it's resolved? Thanks

**Comment by filips123** [comment]
> This is what I've been doing. It won't break SSO if you add the domain of your SSO to the `firefoxpwa.allowedDomains` config as instructed in later comments inside #62.

Yes, this should also work. I probably need to make `firefoxpwa.allowedDomains` discoverable through settings page because even I forgot it exists...

> do you happen to know the issue number for this bug?

I created #95.

**Comment by kbzowski** [comment]
@markcellus: Thank you. It works... sort of. PWA Chat window closes when I click on the link. I don't know if that's intentional or if its a crashing.

**Comment by markcellus** [comment]
Yeah that's odd. Does restarting Firefox after you've made changes resolve it?

**Comment by alchzh** [comment]
Make sure that open links in new window is set as well

**Comment by black7375** [comment]
How about creating a new tab internally when we open an external link?
It'll be nice that the reloading of the PWA app also disappears when we close the external link.

**Comment by filips123** [comment]
> Thank you. It works... sort of. PWA Chat window closes when I click on the link. I don't know if that's intentional or if its a crashing.

Please make sure that you set to open links in new window and restart Firefox as others said.

> How about creating a new tab internally when we open an external link?

This is actually the default behaviour of Firefox but I changed it because there are some bugs. For example, although the link will open in a new hidden/internal tab, closing it will just load the PWA in that tab again instead of closing it and switching to another one. I will try to fix this in the future.

**Comment by filips123** [comment]
> Yes, this should also work. I probably need to make `firefoxpwa.allowedDomains` discoverable through settings page because even I forgot it exists...

This is now done and will be released in the next version. The settings page now has an input that allows users to edit `firefoxpwa.allowedDomains`.

> How about creating a new tab internally when we open an external link?

This will also be available in the next version, but won't be enabled by default. To enable this, you will have to choose "Force links into a new tab" in the settings.

I wanted to make this a default option, but unfortunately, it could cause problems when an external link would open another external link, but closing it would only close the latter, so unused internal tabs could accumulate over time. I also tried to fix this by only opening transitions from PWA to external URLs in a new tab, but unfortunately, I wasn't able to implement this.

**Comment by darkmagi2** [comment]
Not sure if it's user error, but I could never get this to behave the way I wanted. My settings:

**Comment by darkmagi2** [comment]
Not sure if this is user error or what, but I could never get this working as expected. Here are my settings (I also tried "accounts.google.com")
![image](https://user-images.githubusercontent.com/20465830/186801427-74d00294-c24e-427c-9d93-9ac44237f22d.png)

When I click a link in Google Chat, it opens in a new PWA window (no address bar). If I right click and do "open in default browser" it does what I want.

Also, with these settings checked my PWA for Google Voice doesn't work at all (opens in my default browser) but I assume that is a problem with the Domains allowed, haven't really dug into that one just yet.
